create table if not exists public.lineups (
  id bigint generated by default as identity primary key,
  competition_name text not null,
  match_datetime timestamptz not null,
  opponent_name text,
  formation_module text not null,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.lineups
  drop constraint if exists lineups_formation_module_check;

alter table public.lineups
  add constraint lineups_formation_module_check
  check (
    formation_module in (
      '3-4-3 IN LINEA',
      '3-4-1-2',
      '3-4-2-1',
      '3-1-4-2',
      '3-5-2',
      '4-3-3 OFFENSIVO',
      '4-3-3 IN LINEA',
      '4-3-1-2',
      '4-3-2-1',
      '4-5-1',
      '4-3-3 CONTENIMENTO',
      '4-5-1 IN LINEA',
      '4-4-2 IN LINEA',
      '4-4-1-1 AVANZATO',
      '4-1-2-1-2 LARGO',
      '4-1-2-1-2 STRETTO',
      '4-2-2-2',
      '4-3-3 DIFENSIVO',
      '4-4-2 CONTENIMENTO',
      '4-2-4',
      '4-1-3-2',
      '4-1-4-1',
      '4-2-1-3',
      '4-2-3-1 STRETTO',
      '4-2-3-1 LARGO',
      '5-2-3',
      '5-2-1-2',
      '5-4-1 IN LINEA',
      '5-3-2'
    )
  );

do $$
declare
  player_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into player_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'player_profiles'
    and a.attname = 'id'
    and not a.attisdropped;

  if player_id_type is null then
    raise exception 'Column public.player_profiles.id not found';
  end if;

  execute format(
    $sql$
      create table if not exists public.lineup_players (
        id bigint generated by default as identity primary key,
        lineup_id bigint not null
          references public.lineups(id) on delete cascade,
        player_id %s not null
          references public.player_profiles(id) on delete cascade,
        position_code text not null,
        created_at timestamptz not null default timezone('utc', now()),
        constraint lineup_players_unique_player_per_lineup
          unique (lineup_id, player_id),
        constraint lineup_players_unique_position_per_lineup
          unique (lineup_id, position_code)
      );
    $sql$,
    player_id_type
  );
end $$;

create index if not exists lineups_match_datetime_idx
  on public.lineups (match_datetime);

create index if not exists lineup_players_lineup_id_idx
  on public.lineup_players (lineup_id);

create index if not exists lineup_players_player_id_idx
  on public.lineup_players (player_id);

alter table public.lineups enable row level security;
alter table public.lineup_players enable row level security;

drop policy if exists lineups_select_dev on public.lineups;
drop policy if exists lineups_insert_dev on public.lineups;
drop policy if exists lineups_update_dev on public.lineups;
drop policy if exists lineups_delete_dev on public.lineups;

create policy lineups_select_dev
  on public.lineups
  for select
  using (true);

create policy lineups_insert_dev
  on public.lineups
  for insert
  with check (true);

create policy lineups_update_dev
  on public.lineups
  for update
  using (true)
  with check (true);

create policy lineups_delete_dev
  on public.lineups
  for delete
  using (true);

drop policy if exists lineup_players_select_dev on public.lineup_players;
drop policy if exists lineup_players_insert_dev on public.lineup_players;
drop policy if exists lineup_players_update_dev on public.lineup_players;
drop policy if exists lineup_players_delete_dev on public.lineup_players;

create policy lineup_players_select_dev
  on public.lineup_players
  for select
  using (true);

create policy lineup_players_insert_dev
  on public.lineup_players
  for insert
  with check (true);

create policy lineup_players_update_dev
  on public.lineup_players
  for update
  using (true)
  with check (true);

create policy lineup_players_delete_dev
  on public.lineup_players
  for delete
  using (true);
