alter table if exists public.player_profiles
  add column if not exists team_role text not null default 'player';

alter table public.player_profiles
  drop constraint if exists player_profiles_team_role_check;

alter table public.player_profiles
  add constraint player_profiles_team_role_check
  check (team_role in ('player', 'vice_captain', 'captain'));

create table if not exists public.attendance_weeks (
  id bigint generated by default as identity primary key,
  week_start date not null unique,
  week_end date not null,
  selected_dates date[] not null,
  archived_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.attendance_weeks
  drop constraint if exists attendance_weeks_week_bounds_check;

alter table public.attendance_weeks
  add constraint attendance_weeks_week_bounds_check
  check (week_end = week_start + 6);

alter table public.attendance_weeks
  drop constraint if exists attendance_weeks_selected_dates_check;

alter table public.attendance_weeks
  add constraint attendance_weeks_selected_dates_check
  check (cardinality(selected_dates) > 0);

do $$
declare
  player_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into player_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'player_profiles'
    and a.attname = 'id'
    and not a.attisdropped;

  if player_id_type is null then
    raise exception 'Column public.player_profiles.id not found';
  end if;

  execute format(
    $sql$
      create table if not exists public.attendance_entries (
        id bigint generated by default as identity primary key,
        week_id bigint not null
          references public.attendance_weeks(id) on delete cascade,
        player_id %1$s not null
          references public.player_profiles(id) on delete cascade,
        attendance_date date not null,
        availability text not null default 'pending',
        updated_by_player_id %1$s
          references public.player_profiles(id) on delete set null,
        updated_at timestamptz not null default timezone('utc', now()),
        created_at timestamptz not null default timezone('utc', now()),
        constraint attendance_entries_unique_player_per_day
          unique (week_id, player_id, attendance_date),
        constraint attendance_entries_availability_check
          check (availability in ('pending', 'yes', 'no'))
      );
    $sql$,
    player_id_type
  );
end $$;

create index if not exists attendance_weeks_week_start_idx
  on public.attendance_weeks (week_start desc);

create index if not exists attendance_weeks_archived_at_idx
  on public.attendance_weeks (archived_at);

create index if not exists attendance_entries_week_id_idx
  on public.attendance_entries (week_id);

create index if not exists attendance_entries_player_id_idx
  on public.attendance_entries (player_id);

create index if not exists attendance_entries_attendance_date_idx
  on public.attendance_entries (attendance_date);

create or replace function public.attendance_calendar_week_start(
  reference_date date
)
returns date
language sql
immutable
as $$
  select reference_date - (extract(isodow from reference_date)::int - 1);
$$;

create or replace function public.sync_attendance_entries_for_week(
  target_week_id bigint
)
returns void
language sql
as $$
  insert into public.attendance_entries (
    week_id,
    player_id,
    attendance_date,
    availability
  )
  select
    target_week_id,
    player.id,
    selected_day.attendance_date,
    'pending'
  from public.player_profiles as player
  join public.attendance_weeks as week
    on week.id = target_week_id
  cross join unnest(week.selected_dates) as selected_day(attendance_date)
  left join public.attendance_entries as entry
    on entry.week_id = target_week_id
   and entry.player_id = player.id
   and entry.attendance_date = selected_day.attendance_date
  where entry.id is null;
$$;

create or replace function public.create_attendance_week(
  reference_date date,
  selected_dates date[]
)
returns bigint
language plpgsql
as $$
declare
  target_week_start date;
  target_week_end date;
  normalized_dates date[];
  target_week_id bigint;
begin
  if reference_date is null then
    raise exception 'Specifica una data valida per la settimana presenze';
  end if;

  target_week_start := public.attendance_calendar_week_start(reference_date);
  target_week_end := target_week_start + 6;

  select array_agg(distinct selected_date order by selected_date)
    into normalized_dates
  from unnest(selected_dates) as selected_date
  where selected_date between target_week_start and target_week_end;

  if normalized_dates is null or cardinality(normalized_dates) = 0 then
    raise exception 'Seleziona almeno un giorno valido per la settimana scelta';
  end if;

  if exists (
    select 1
    from unnest(selected_dates) as selected_date
    where selected_date < target_week_start
       or selected_date > target_week_end
  ) then
    raise exception 'Tutti i giorni selezionati devono appartenere alla stessa settimana';
  end if;

  if exists (
    select 1
    from public.attendance_weeks
    where archived_at is null
  ) then
    raise exception 'Archivia prima la settimana presenze attiva';
  end if;

  insert into public.attendance_weeks (
    week_start,
    week_end,
    selected_dates
  )
  values (
    target_week_start,
    target_week_end,
    normalized_dates
  )
  returning id into target_week_id;

  perform public.sync_attendance_entries_for_week(target_week_id);

  return target_week_id;
end;
$$;

create or replace function public.archive_attendance_week(
  target_week_id bigint
)
returns bigint
language plpgsql
as $$
declare
  archived_week_id bigint;
begin
  update public.attendance_weeks
  set archived_at = timezone('utc', now())
  where id = target_week_id
    and archived_at is null
  returning id into archived_week_id;

  return archived_week_id;
end;
$$;

create or replace function public.restore_attendance_week(
  target_week_id bigint
)
returns bigint
language plpgsql
as $$
declare
  restored_week_id bigint;
begin
  if exists (
    select 1
    from public.attendance_weeks
    where archived_at is null
      and id <> target_week_id
  ) then
    raise exception 'Esiste gia una settimana presenze attiva';
  end if;

  update public.attendance_weeks
  set archived_at = null
  where id = target_week_id
    and archived_at is not null
  returning id into restored_week_id;

  if restored_week_id is null then
    raise exception 'La settimana selezionata non puo essere ripristinata';
  end if;

  perform public.sync_attendance_entries_for_week(restored_week_id);

  return restored_week_id;
end;
$$;

grant execute on function public.sync_attendance_entries_for_week(bigint)
  to anon, authenticated;

grant execute on function public.create_attendance_week(date, date[])
  to anon, authenticated;

grant execute on function public.archive_attendance_week(bigint)
  to anon, authenticated;

grant execute on function public.restore_attendance_week(bigint)
  to anon, authenticated;

drop function if exists public.ensure_active_attendance_week(timestamptz);
drop function if exists public.attendance_target_week_start(timestamptz);
drop function if exists public.manual_attendance_target_week_start(timestamptz);
drop function if exists public.activate_attendance_week_manually(timestamptz);

alter table public.attendance_weeks enable row level security;
alter table public.attendance_entries enable row level security;

drop policy if exists attendance_weeks_select_dev on public.attendance_weeks;
drop policy if exists attendance_weeks_insert_dev on public.attendance_weeks;
drop policy if exists attendance_weeks_update_dev on public.attendance_weeks;
drop policy if exists attendance_weeks_delete_dev on public.attendance_weeks;

create policy attendance_weeks_select_dev
  on public.attendance_weeks
  for select
  using (true);

create policy attendance_weeks_insert_dev
  on public.attendance_weeks
  for insert
  with check (true);

create policy attendance_weeks_update_dev
  on public.attendance_weeks
  for update
  using (true)
  with check (true);

create policy attendance_weeks_delete_dev
  on public.attendance_weeks
  for delete
  using (true);

drop policy if exists attendance_entries_select_dev on public.attendance_entries;
drop policy if exists attendance_entries_insert_dev on public.attendance_entries;
drop policy if exists attendance_entries_update_dev on public.attendance_entries;
drop policy if exists attendance_entries_delete_dev on public.attendance_entries;

create policy attendance_entries_select_dev
  on public.attendance_entries
  for select
  using (true);

create policy attendance_entries_insert_dev
  on public.attendance_entries
  for insert
  with check (true);

create policy attendance_entries_update_dev
  on public.attendance_entries
  for update
  using (true)
  with check (true);

create policy attendance_entries_delete_dev
  on public.attendance_entries
  for delete
  using (true);
