begin;

alter table public.club_permission_settings
  add column if not exists vice_manage_invites boolean not null default false;

create table if not exists public.club_invites (
  id bigint generated by default as identity primary key,
  club_id bigint not null
    references public.clubs(id) on delete cascade,
  created_by_user_id uuid
    references auth.users(id) on delete set null,
  created_by_membership_id bigint
    references public.memberships(id) on delete set null,
  target_user_id uuid not null
    references auth.users(id) on delete cascade,
  target_player_profile_id bigint
    references public.player_profiles(id) on delete set null,
  target_account_email text,
  target_nome text not null,
  target_cognome text not null,
  target_id_console text,
  target_primary_role text,
  status text not null default 'pending',
  resolved_at timestamptz,
  resolved_by_user_id uuid
    references auth.users(id) on delete set null,
  resolved_by_membership_id bigint
    references public.memberships(id) on delete set null,
  accepted_membership_id bigint
    references public.memberships(id) on delete set null,
  accepted_player_id bigint
    references public.player_profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint club_invites_status_check
    check (status in ('pending', 'accepted', 'declined', 'revoked', 'expired')),
  constraint club_invites_target_nome_not_blank
    check (char_length(btrim(target_nome)) > 0),
  constraint club_invites_target_cognome_not_blank
    check (char_length(btrim(target_cognome)) > 0),
  constraint club_invites_target_account_email_check
    check (
      target_account_email is null
      or (
        trim(target_account_email) <> ''
        and position('@' in target_account_email) > 1
      )
    ),
  constraint club_invites_self_invite_check
    check (created_by_user_id is null or created_by_user_id <> target_user_id)
);

drop trigger if exists club_invites_touch_updated_at on public.club_invites;

create trigger club_invites_touch_updated_at
before update on public.club_invites
for each row
execute function public.touch_clubline_updated_at();

create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null
    references auth.users(id) on delete cascade,
  club_id bigint
    references public.clubs(id) on delete set null,
  notification_type text not null,
  title text not null,
  body text,
  metadata jsonb not null default '{}'::jsonb,
  related_invite_id bigint
    references public.club_invites(id) on delete set null,
  read_at timestamptz,
  dedupe_key text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint app_notifications_type_check
    check (
      notification_type in (
        'club_invite_received',
        'club_invite_accepted',
        'club_invite_declined',
        'club_invite_revoked',
        'lineup_published',
        'attendance_published'
      )
    ),
  constraint app_notifications_title_not_blank
    check (char_length(btrim(title)) > 0),
  constraint app_notifications_metadata_is_object_check
    check (jsonb_typeof(metadata) = 'object')
);

create index if not exists club_invites_club_status_created_idx
  on public.club_invites (club_id, status, created_at desc);

create index if not exists club_invites_target_status_created_idx
  on public.club_invites (target_user_id, status, created_at desc);

create index if not exists club_invites_target_profile_idx
  on public.club_invites (target_player_profile_id)
  where target_player_profile_id is not null;

create unique index if not exists club_invites_pending_same_club_target_unique
  on public.club_invites (club_id, target_user_id)
  where status = 'pending';

create index if not exists app_notifications_recipient_created_idx
  on public.app_notifications (recipient_user_id, created_at desc);

create index if not exists app_notifications_recipient_unread_created_idx
  on public.app_notifications (recipient_user_id, created_at desc)
  where read_at is null;

create index if not exists app_notifications_related_invite_idx
  on public.app_notifications (related_invite_id)
  where related_invite_id is not null;

create unique index if not exists app_notifications_recipient_dedupe_unique
  on public.app_notifications (recipient_user_id, dedupe_key)
  where dedupe_key is not null;

create or replace function public.clubline_current_user_can_manage_invites_for_club(
  target_club_id bigint
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.memberships as membership
    left join public.club_permission_settings as permissions
      on permissions.club_id = membership.club_id
    where membership.auth_user_id = auth.uid()
      and membership.club_id = target_club_id
      and membership.status = 'active'
      and (
        membership.role = 'captain'
        or (
          membership.role = 'vice_captain'
          and coalesce(permissions.vice_manage_invites, false)
        )
      )
  )
$$;

create or replace function public.clubline_lock_user_membership_flow(
  target_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_user_id is null then
    raise exception using
      errcode = '22023',
      message = 'Utente target non valido',
      detail = 'invalid_target_user';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('clubline-membership-flow:' || target_user_id::text, 0)
  );
end;
$$;

create or replace function public.clubline_create_notification(
  p_recipient_user_id uuid,
  p_club_id bigint,
  p_notification_type text,
  p_title text,
  p_body text default null,
  p_metadata jsonb default '{}'::jsonb,
  p_related_invite_id bigint default null,
  p_dedupe_key text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_notification_id bigint;
  v_notification_type text := public.clubline_normalize_text(p_notification_type);
begin
  if p_recipient_user_id is null then
    raise exception using
      errcode = '22023',
      message = 'Destinatario notifica non valido',
      detail = 'invalid_notification_recipient';
  end if;

  if v_notification_type is null then
    raise exception using
      errcode = '22023',
      message = 'Tipo notifica obbligatorio',
      detail = 'notification_type_required';
  end if;

  if public.clubline_normalize_text(p_title) is null then
    raise exception using
      errcode = '22023',
      message = 'Titolo notifica obbligatorio',
      detail = 'notification_title_required';
  end if;

  if coalesce(jsonb_typeof(coalesce(p_metadata, '{}'::jsonb)), 'null') <> 'object' then
    raise exception using
      errcode = '22023',
      message = 'Metadata notifica non validi',
      detail = 'invalid_notification_metadata';
  end if;

  insert into public.app_notifications (
    recipient_user_id,
    club_id,
    notification_type,
    title,
    body,
    metadata,
    related_invite_id,
    dedupe_key
  )
  values (
    p_recipient_user_id,
    p_club_id,
    v_notification_type,
    btrim(p_title),
    public.clubline_normalize_text(p_body),
    coalesce(p_metadata, '{}'::jsonb),
    p_related_invite_id,
    public.clubline_normalize_text(p_dedupe_key)
  )
  on conflict (recipient_user_id, dedupe_key)
  where dedupe_key is not null
  do update
    set club_id = excluded.club_id,
        notification_type = excluded.notification_type,
        title = excluded.title,
        body = excluded.body,
        metadata = excluded.metadata,
        related_invite_id = coalesce(excluded.related_invite_id, public.app_notifications.related_invite_id)
  returning id into v_notification_id;

  return v_notification_id;
end;
$$;

create or replace function public.clubline_create_club_invite(
  p_actor_user_id uuid,
  p_target_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_membership public.memberships%rowtype;
  v_permissions public.club_permission_settings%rowtype;
  v_target_player public.player_profiles%rowtype;
  v_target_active_membership public.memberships%rowtype;
  v_pending_join_request public.join_requests%rowtype;
  v_existing_invite public.club_invites%rowtype;
  v_club public.clubs%rowtype;
  v_invite public.club_invites%rowtype;
  v_target_email text;
  v_target_nome text;
  v_target_cognome text;
  v_notification_id bigint;
begin
  if p_actor_user_id is null or p_target_user_id is null then
    raise exception using
      errcode = '22023',
      message = 'Utenti invito non validi',
      detail = 'invalid_invite_users';
  end if;

  if p_actor_user_id = p_target_user_id then
    raise exception using
      errcode = 'P0001',
      message = 'Non puoi invitare te stesso',
      detail = 'self_invite_forbidden';
  end if;

  select *
    into v_actor_membership
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if not found then
    raise exception using
      errcode = '42501',
      message = 'Devi appartenere a un club per inviare un invito',
      detail = 'invite_management_forbidden';
  end if;

  select *
    into v_permissions
  from public.club_permission_settings
  where club_id = v_actor_membership.club_id;

  if not (
    v_actor_membership.role = 'captain'
    or (
      v_actor_membership.role = 'vice_captain'
      and coalesce(v_permissions.vice_manage_invites, false)
    )
  ) then
    raise exception using
      errcode = '42501',
      message = 'Non hai i permessi per gestire gli inviti del club',
      detail = 'invite_management_forbidden';
  end if;

  perform public.clubline_lock_user_membership_flow(p_target_user_id);

  select email
    into v_target_email
  from auth.users
  where id = p_target_user_id;

  if not found then
    raise exception using
      errcode = '22023',
      message = 'Utente di destinazione non trovato',
      detail = 'target_user_not_found';
  end if;

  select *
    into v_target_active_membership
  from public.memberships
  where auth_user_id = p_target_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using
      errcode = 'P0001',
      message = 'L utente appartiene gia a un club attivo',
      detail = 'target_user_has_active_membership';
  end if;

  select *
    into v_pending_join_request
  from public.join_requests
  where requester_user_id = p_target_user_id
    and status = 'pending'
  order by created_at asc, id asc
  limit 1
  for update;

  if found then
    if v_pending_join_request.club_id = v_actor_membership.club_id then
      raise exception using
        errcode = 'P0001',
        message = 'Esiste gia una richiesta di ingresso pendente per questo club',
        detail = 'pending_join_request_same_club';
    end if;

    raise exception using
      errcode = 'P0001',
      message = 'L utente ha una richiesta di ingresso pendente verso un altro club',
      detail = 'pending_join_request_other_club';
  end if;

  select *
    into v_existing_invite
  from public.club_invites
  where club_id = v_actor_membership.club_id
    and target_user_id = p_target_user_id
    and status = 'pending'
  order by created_at desc, id desc
  limit 1
  for update;

  if found then
    raise exception using
      errcode = 'P0001',
      message = 'Esiste gia un invito pendente per questo utente in questo club',
      detail = 'pending_club_invite_exists';
  end if;

  select *
    into v_target_player
  from public.player_profiles
  where auth_user_id = p_target_user_id
    and archived_at is null
  order by
    case
      when club_id is null and membership_id is null then 0
      else 1
    end asc,
    created_at desc nulls last,
    id desc
  limit 1
  for update;

  v_target_nome := coalesce(
    public.clubline_normalize_text(v_target_player.nome),
    public.clubline_normalize_text(
      initcap(
        split_part(
          regexp_replace(split_part(coalesce(v_target_email, ''), '@', 1), '[^a-zA-Z0-9]+', ' ', 'g'),
          ' ',
          1
        )
      )
    ),
    'Nuovo'
  );
  v_target_cognome := coalesce(
    public.clubline_normalize_text(v_target_player.cognome),
    'Membro'
  );

  select *
    into v_club
  from public.clubs
  where id = v_actor_membership.club_id;

  begin
    insert into public.club_invites (
      club_id,
      created_by_user_id,
      created_by_membership_id,
      target_user_id,
      target_player_profile_id,
      target_account_email,
      target_nome,
      target_cognome,
      target_id_console,
      target_primary_role,
      status
    )
    values (
      v_actor_membership.club_id,
      p_actor_user_id,
      v_actor_membership.id,
      p_target_user_id,
      v_target_player.id,
      public.clubline_normalize_email(coalesce(v_target_player.account_email, v_target_email)),
      v_target_nome,
      v_target_cognome,
      public.clubline_normalize_text(v_target_player.id_console),
      public.clubline_normalize_text(v_target_player.primary_role),
      'pending'
    )
    returning * into v_invite;
  exception
    when unique_violation then
      raise exception using
        errcode = 'P0001',
        message = 'Esiste gia un invito pendente per questo utente in questo club',
        detail = 'pending_club_invite_exists';
  end;

  v_notification_id := public.clubline_create_notification(
    p_target_user_id,
    v_actor_membership.club_id,
    'club_invite_received',
    'Hai ricevuto un invito al club ' || coalesce(v_club.name, 'Clubline'),
    'Apri l app per accettare o rifiutare l invito.',
    jsonb_build_object(
      'redirect', jsonb_build_object(
        'screen', 'notifications',
        'entity', 'club_invite',
        'invite_id', v_invite.id
      ),
      'invite_id', v_invite.id,
      'club_id', v_actor_membership.club_id
    ),
    v_invite.id,
    'club_invite_received:' || v_invite.id::text
  );

  perform public.clubline_log_event(
    v_actor_membership.club_id,
    v_actor_membership.id,
    p_actor_user_id,
    p_target_user_id,
    'invite_created',
    jsonb_build_object(
      'invite_id', v_invite.id,
      'notification_id', v_notification_id
    )
  );

  return jsonb_build_object(
    'invite_id', v_invite.id,
    'club_id', v_invite.club_id,
    'target_user_id', v_invite.target_user_id,
    'notification_id', v_notification_id
  );
end;
$$;

create or replace function public.clubline_revoke_club_invite(
  p_actor_user_id uuid,
  p_invite_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_membership public.memberships%rowtype;
  v_permissions public.club_permission_settings%rowtype;
  v_invite public.club_invites%rowtype;
  v_club public.clubs%rowtype;
  v_now timestamptz := timezone('utc', now());
  v_notification_id bigint;
begin
  select *
    into v_actor_membership
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if not found then
    raise exception using
      errcode = '42501',
      message = 'Devi appartenere a un club per revocare un invito',
      detail = 'invite_management_forbidden';
  end if;

  select *
    into v_permissions
  from public.club_permission_settings
  where club_id = v_actor_membership.club_id;

  if not (
    v_actor_membership.role = 'captain'
    or (
      v_actor_membership.role = 'vice_captain'
      and coalesce(v_permissions.vice_manage_invites, false)
    )
  ) then
    raise exception using
      errcode = '42501',
      message = 'Non hai i permessi per gestire gli inviti del club',
      detail = 'invite_management_forbidden';
  end if;

  select *
    into v_invite
  from public.club_invites
  where id = p_invite_id
  for update;

  if not found then
    raise exception using
      errcode = '22023',
      message = 'Invito non trovato',
      detail = 'invite_not_found';
  end if;

  if v_invite.club_id <> v_actor_membership.club_id then
    raise exception using
      errcode = '42501',
      message = 'Non puoi revocare inviti di un altro club',
      detail = 'invite_management_forbidden';
  end if;

  if v_invite.status <> 'pending' then
    raise exception using
      errcode = 'P0001',
      message = 'Questo invito e gia stato gestito',
      detail = 'invite_not_pending';
  end if;

  update public.club_invites
  set status = 'revoked',
      resolved_at = v_now,
      resolved_by_user_id = p_actor_user_id,
      resolved_by_membership_id = v_actor_membership.id
  where id = v_invite.id
  returning * into v_invite;

  update public.app_notifications
  set read_at = coalesce(read_at, v_now)
  where related_invite_id = v_invite.id
    and notification_type = 'club_invite_received'
    and recipient_user_id = v_invite.target_user_id;

  select *
    into v_club
  from public.clubs
  where id = v_invite.club_id;

  v_notification_id := public.clubline_create_notification(
    v_invite.target_user_id,
    v_invite.club_id,
    'club_invite_revoked',
    'Invito revocato per il club ' || coalesce(v_club.name, 'Clubline'),
    'L invito al club e stato revocato.',
    jsonb_build_object(
      'redirect', jsonb_build_object(
        'screen', 'notifications',
        'entity', 'club_invite',
        'invite_id', v_invite.id
      ),
      'invite_id', v_invite.id,
      'club_id', v_invite.club_id
    ),
    v_invite.id,
    'club_invite_revoked:' || v_invite.id::text
  );

  perform public.clubline_log_event(
    v_invite.club_id,
    v_actor_membership.id,
    p_actor_user_id,
    v_invite.target_user_id,
    'invite_revoked',
    jsonb_build_object(
      'invite_id', v_invite.id,
      'notification_id', v_notification_id
    )
  );

  return jsonb_build_object(
    'invite_id', v_invite.id,
    'status', v_invite.status
  );
end;
$$;

create or replace function public.clubline_accept_club_invite(
  p_actor_user_id uuid,
  p_invite_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.club_invites%rowtype;
  v_existing_membership public.memberships%rowtype;
  v_membership public.memberships%rowtype;
  v_expired_invite public.club_invites%rowtype;
  v_expired_invite_ids bigint[] := '{}'::bigint[];
  v_club public.clubs%rowtype;
  v_player_id bigint;
  v_now timestamptz := timezone('utc', now());
  v_notification_id bigint;
begin
  select *
    into v_invite
  from public.club_invites
  where id = p_invite_id;

  if not found then
    raise exception using
      errcode = '22023',
      message = 'Invito non trovato',
      detail = 'invite_not_found';
  end if;

  if v_invite.target_user_id <> p_actor_user_id then
    raise exception using
      errcode = '42501',
      message = 'Questo invito non appartiene all utente corrente',
      detail = 'invite_not_owned';
  end if;

  perform public.clubline_lock_user_membership_flow(p_actor_user_id);

  select *
    into v_invite
  from public.club_invites
  where id = p_invite_id
  for update;

  if not found then
    raise exception using
      errcode = '22023',
      message = 'Invito non trovato',
      detail = 'invite_not_found';
  end if;

  if v_invite.target_user_id <> p_actor_user_id then
    raise exception using
      errcode = '42501',
      message = 'Questo invito non appartiene all utente corrente',
      detail = 'invite_not_owned';
  end if;

  if v_invite.status <> 'pending' then
    raise exception using
      errcode = 'P0001',
      message = 'Questo invito e gia stato gestito',
      detail = 'invite_not_pending';
  end if;

  select *
    into v_existing_membership
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using
      errcode = 'P0001',
      message = 'Appartieni gia a un club attivo',
      detail = 'target_user_has_active_membership';
  end if;

  perform 1
  from public.join_requests
  where requester_user_id = p_actor_user_id
    and status = 'pending'
  for update;

  begin
    insert into public.memberships (
      club_id,
      auth_user_id,
      role,
      status
    )
    values (
      v_invite.club_id,
      p_actor_user_id,
      'player',
      'active'
    )
    returning * into v_membership;
  exception
    when unique_violation then
      raise exception using
        errcode = 'P0001',
        message = 'Appartieni gia a un club attivo',
        detail = 'target_user_has_active_membership';
  end;

  v_player_id := public.clubline_attach_player_profile(
    v_membership.id,
    p_actor_user_id,
    v_invite.target_account_email,
    v_invite.target_nome,
    v_invite.target_cognome,
    v_invite.target_id_console,
    null,
    v_invite.target_primary_role,
    'player'
  );

  update public.club_invites
  set status = 'accepted',
      resolved_at = v_now,
      resolved_by_user_id = p_actor_user_id,
      resolved_by_membership_id = v_membership.id,
      accepted_membership_id = v_membership.id,
      accepted_player_id = v_player_id
  where id = v_invite.id
  returning * into v_invite;

  update public.join_requests
  set status = 'expired',
      decided_at = v_now,
      decided_by_membership_id = null
  where requester_user_id = p_actor_user_id
    and status = 'pending';

  for v_expired_invite in
    update public.club_invites
    set status = 'expired',
        resolved_at = v_now,
        resolved_by_user_id = p_actor_user_id,
        resolved_by_membership_id = v_membership.id
    where target_user_id = p_actor_user_id
      and status = 'pending'
      and id <> v_invite.id
    returning *
  loop
    v_expired_invite_ids := array_append(v_expired_invite_ids, v_expired_invite.id);

    perform public.clubline_log_event(
      v_expired_invite.club_id,
      null,
      p_actor_user_id,
      p_actor_user_id,
      'invite_expired',
      jsonb_build_object(
        'invite_id', v_expired_invite.id,
        'reason', 'invite_accepted',
        'accepted_invite_id', v_invite.id,
        'accepted_membership_id', v_membership.id
      )
    );
  end loop;

  update public.app_notifications
  set read_at = coalesce(read_at, v_now)
  where recipient_user_id = p_actor_user_id
    and notification_type = 'club_invite_received'
    and (
      related_invite_id = v_invite.id
      or (
        cardinality(v_expired_invite_ids) > 0
        and related_invite_id = any(v_expired_invite_ids)
      )
    );

  select *
    into v_club
  from public.clubs
  where id = v_invite.club_id;

  if v_invite.created_by_user_id is not null then
    v_notification_id := public.clubline_create_notification(
      v_invite.created_by_user_id,
      v_invite.club_id,
      'club_invite_accepted',
      v_invite.target_nome || ' ' || v_invite.target_cognome || ' ha accettato l invito',
      'Il giocatore e entrato nel club ' || coalesce(v_club.name, 'Clubline') || '.',
      jsonb_build_object(
        'redirect', jsonb_build_object(
          'screen', 'club_management',
          'entity', 'club_invite',
          'invite_id', v_invite.id
        ),
        'invite_id', v_invite.id,
        'club_id', v_invite.club_id,
        'membership_id', v_membership.id,
        'player_id', v_player_id
      ),
      v_invite.id,
      'club_invite_accepted:' || v_invite.id::text
    );
  else
    v_notification_id := null;
  end if;

  perform public.clubline_log_event(
    v_invite.club_id,
    v_membership.id,
    p_actor_user_id,
    p_actor_user_id,
    'invite_accepted',
    jsonb_build_object(
      'invite_id', v_invite.id,
      'membership_id', v_membership.id,
      'player_id', v_player_id,
      'notification_id', v_notification_id
    )
  );

  return jsonb_build_object(
    'invite_id', v_invite.id,
    'club_id', v_invite.club_id,
    'membership_id', v_membership.id,
    'player_id', v_player_id,
    'status', v_invite.status
  );
end;
$$;

create or replace function public.clubline_decline_club_invite(
  p_actor_user_id uuid,
  p_invite_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.club_invites%rowtype;
  v_club public.clubs%rowtype;
  v_now timestamptz := timezone('utc', now());
  v_notification_id bigint;
begin
  select *
    into v_invite
  from public.club_invites
  where id = p_invite_id;

  if not found then
    raise exception using
      errcode = '22023',
      message = 'Invito non trovato',
      detail = 'invite_not_found';
  end if;

  if v_invite.target_user_id <> p_actor_user_id then
    raise exception using
      errcode = '42501',
      message = 'Questo invito non appartiene all utente corrente',
      detail = 'invite_not_owned';
  end if;

  select *
    into v_invite
  from public.club_invites
  where id = p_invite_id
  for update;

  if not found then
    raise exception using
      errcode = '22023',
      message = 'Invito non trovato',
      detail = 'invite_not_found';
  end if;

  if v_invite.target_user_id <> p_actor_user_id then
    raise exception using
      errcode = '42501',
      message = 'Questo invito non appartiene all utente corrente',
      detail = 'invite_not_owned';
  end if;

  if v_invite.status <> 'pending' then
    raise exception using
      errcode = 'P0001',
      message = 'Questo invito e gia stato gestito',
      detail = 'invite_not_pending';
  end if;

  update public.club_invites
  set status = 'declined',
      resolved_at = v_now,
      resolved_by_user_id = p_actor_user_id,
      resolved_by_membership_id = null
  where id = v_invite.id
  returning * into v_invite;

  update public.app_notifications
  set read_at = coalesce(read_at, v_now)
  where related_invite_id = v_invite.id
    and notification_type = 'club_invite_received'
    and recipient_user_id = p_actor_user_id;

  select *
    into v_club
  from public.clubs
  where id = v_invite.club_id;

  if v_invite.created_by_user_id is not null then
    v_notification_id := public.clubline_create_notification(
      v_invite.created_by_user_id,
      v_invite.club_id,
      'club_invite_declined',
      v_invite.target_nome || ' ' || v_invite.target_cognome || ' ha rifiutato l invito',
      'Il giocatore non entrera nel club ' || coalesce(v_club.name, 'Clubline') || '.',
      jsonb_build_object(
        'redirect', jsonb_build_object(
          'screen', 'club_management',
          'entity', 'club_invite',
          'invite_id', v_invite.id
        ),
        'invite_id', v_invite.id,
        'club_id', v_invite.club_id
      ),
      v_invite.id,
      'club_invite_declined:' || v_invite.id::text
    );
  else
    v_notification_id := null;
  end if;

  perform public.clubline_log_event(
    v_invite.club_id,
    null,
    p_actor_user_id,
    p_actor_user_id,
    'invite_declined',
    jsonb_build_object(
      'invite_id', v_invite.id,
      'notification_id', v_notification_id
    )
  );

  return jsonb_build_object(
    'invite_id', v_invite.id,
    'status', v_invite.status
  );
end;
$$;

create or replace function public.clubline_create_club(
  p_actor_user_id uuid,
  p_actor_email text,
  p_name text,
  p_owner_nome text,
  p_owner_cognome text,
  p_owner_id_console text,
  p_owner_shirt_number integer default null,
  p_owner_primary_role text default null,
  p_primary_color text default null,
  p_accent_color text default null,
  p_surface_color text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := public.clubline_normalize_text(p_name);
  v_owner_nome text := public.clubline_normalize_text(p_owner_nome);
  v_owner_cognome text := public.clubline_normalize_text(p_owner_cognome);
  v_owner_console text := public.clubline_normalize_text(p_owner_id_console);
  v_slug text;
  v_club public.clubs%rowtype;
  v_membership public.memberships%rowtype;
  v_expired_invite public.club_invites%rowtype;
  v_expired_invite_ids bigint[] := '{}'::bigint[];
  v_player_id bigint;
  v_now timestamptz := timezone('utc', now());
begin
  if v_name is null then
    raise exception using errcode = '22023', message = 'Inserisci un nome club valido';
  end if;
  if v_owner_nome is null or v_owner_cognome is null or v_owner_console is null then
    raise exception using errcode = '22023', message = 'Inserisci nome, cognome e ID console del capitano';
  end if;

  perform public.clubline_lock_user_membership_flow(p_actor_user_id);

  perform 1
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Appartieni gia a un club attivo';
  end if;

  perform 1
  from public.join_requests
  where requester_user_id = p_actor_user_id
    and status = 'pending'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Hai gia una richiesta di ingresso pendente';
  end if;

  v_slug := public.clubline_next_club_slug(v_name);

  insert into public.clubs (
    name,
    normalized_name,
    slug,
    primary_color,
    accent_color,
    surface_color,
    created_by_user_id
  )
  values (
    v_name,
    lower(v_name),
    v_slug,
    coalesce(public.clubline_normalize_text(p_primary_color), '#1F2937'),
    coalesce(public.clubline_normalize_text(p_accent_color), '#0F766E'),
    coalesce(public.clubline_normalize_text(p_surface_color), '#0F172A'),
    p_actor_user_id
  )
  returning * into v_club;

  insert into public.club_settings (
    club_id,
    additional_links
  )
  values (
    v_club.id,
    '[]'::jsonb
  )
  on conflict (club_id) do nothing;

  insert into public.club_permission_settings (
    club_id,
    vice_manage_players,
    vice_manage_lineups,
    vice_manage_streams,
    vice_manage_attendance,
    vice_manage_team_info
  )
  values (
    v_club.id,
    false,
    false,
    false,
    false,
    false
  )
  on conflict (club_id) do nothing;

  begin
    insert into public.memberships (
      club_id,
      auth_user_id,
      role,
      status
    )
    values (
      v_club.id,
      p_actor_user_id,
      'captain',
      'active'
    )
    returning * into v_membership;
  exception
    when unique_violation then
      raise exception using errcode = 'P0001', message = 'Appartieni gia a un club attivo';
  end;

  v_player_id := public.clubline_attach_player_profile(
    v_membership.id,
    p_actor_user_id,
    p_actor_email,
    v_owner_nome,
    v_owner_cognome,
    v_owner_console,
    p_owner_shirt_number,
    p_owner_primary_role,
    'captain'
  );

  for v_expired_invite in
    update public.club_invites
    set status = 'expired',
        resolved_at = v_now,
        resolved_by_user_id = p_actor_user_id,
        resolved_by_membership_id = v_membership.id
    where target_user_id = p_actor_user_id
      and status = 'pending'
    returning *
  loop
    v_expired_invite_ids := array_append(v_expired_invite_ids, v_expired_invite.id);

    perform public.clubline_log_event(
      v_expired_invite.club_id,
      null,
      p_actor_user_id,
      p_actor_user_id,
      'invite_expired',
      jsonb_build_object(
        'invite_id', v_expired_invite.id,
        'reason', 'club_created',
        'club_id', v_club.id,
        'membership_id', v_membership.id
      )
    );
  end loop;

  if cardinality(v_expired_invite_ids) > 0 then
    update public.app_notifications
    set read_at = coalesce(read_at, v_now)
    where recipient_user_id = p_actor_user_id
      and notification_type = 'club_invite_received'
      and related_invite_id = any(v_expired_invite_ids);
  end if;

  perform public.clubline_log_event(
    v_club.id,
    v_membership.id,
    p_actor_user_id,
    p_actor_user_id,
    'club_created',
    jsonb_build_object(
      'club_id', v_club.id,
      'membership_id', v_membership.id,
      'player_id', v_player_id
    )
  );

  return jsonb_build_object(
    'club_id', v_club.id,
    'membership_id', v_membership.id,
    'player_id', v_player_id
  );
end;
$$;

create or replace function public.clubline_request_join_club(
  p_actor_user_id uuid,
  p_actor_email text,
  p_club_id bigint,
  p_requested_nome text,
  p_requested_cognome text,
  p_requested_shirt_number integer default null,
  p_requested_primary_role text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nome text := coalesce(public.clubline_normalize_text(p_requested_nome), 'Clubline');
  v_cognome text := coalesce(public.clubline_normalize_text(p_requested_cognome), 'Player');
  v_request public.join_requests%rowtype;
begin
  perform public.clubline_lock_user_membership_flow(p_actor_user_id);

  perform 1
  from public.clubs
  where id = p_club_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Club non trovato';
  end if;

  perform 1
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Appartieni gia a un club attivo';
  end if;

  perform 1
  from public.join_requests
  where requester_user_id = p_actor_user_id
    and status = 'pending'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Hai gia una richiesta di ingresso pendente';
  end if;

  begin
    insert into public.join_requests (
      club_id,
      requester_user_id,
      requester_email,
      requested_nome,
      requested_cognome,
      requested_shirt_number,
      requested_primary_role,
      status
    )
    values (
      p_club_id,
      p_actor_user_id,
      public.clubline_normalize_email(p_actor_email),
      v_nome,
      v_cognome,
      p_requested_shirt_number,
      public.clubline_normalize_text(p_requested_primary_role),
      'pending'
    )
    returning * into v_request;
  exception
    when unique_violation then
      raise exception using errcode = 'P0001', message = 'Hai gia una richiesta di ingresso pendente';
  end;

  perform public.clubline_log_event(
    v_request.club_id,
    null,
    p_actor_user_id,
    p_actor_user_id,
    'join_requested',
    jsonb_build_object('join_request_id', v_request.id)
  );

  return jsonb_build_object('join_request_id', v_request.id);
end;
$$;

create or replace function public.clubline_approve_join_request(
  p_actor_user_id uuid,
  p_join_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.join_requests%rowtype;
  v_captain public.memberships%rowtype;
  v_membership public.memberships%rowtype;
  v_expired_invite public.club_invites%rowtype;
  v_expired_invite_ids bigint[] := '{}'::bigint[];
  v_player_id bigint;
  v_now timestamptz := timezone('utc', now());
begin
  select *
    into v_request
  from public.join_requests
  where id = p_join_request_id;

  if not found then
    raise exception using errcode = '22023', message = 'Richiesta di ingresso non trovata';
  end if;

  perform public.clubline_lock_user_membership_flow(v_request.requester_user_id);

  select *
    into v_request
  from public.join_requests
  where id = p_join_request_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Richiesta di ingresso non trovata';
  end if;
  if v_request.status <> 'pending' then
    raise exception using errcode = 'P0001', message = 'Questa richiesta di ingresso e gia stata gestita';
  end if;

  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and club_id = v_request.club_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano del club puo approvare la richiesta';
  end if;

  perform 1
  from public.memberships
  where auth_user_id = v_request.requester_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'L utente appartiene gia a un club';
  end if;

  begin
    insert into public.memberships (
      club_id,
      auth_user_id,
      role,
      status
    )
    values (
      v_request.club_id,
      v_request.requester_user_id,
      'player',
      'active'
    )
    returning * into v_membership;
  exception
    when unique_violation then
      raise exception using errcode = 'P0001', message = 'L utente appartiene gia a un club';
  end;

  v_player_id := public.clubline_attach_player_profile(
    v_membership.id,
    v_request.requester_user_id,
    v_request.requester_email,
    v_request.requested_nome,
    v_request.requested_cognome,
    null,
    v_request.requested_shirt_number,
    v_request.requested_primary_role,
    'player'
  );

  update public.join_requests
  set status = 'approved',
      decided_by_membership_id = v_captain.id,
      decided_at = v_now
  where id = v_request.id;

  update public.join_requests
  set status = 'expired',
      decided_by_membership_id = v_captain.id,
      decided_at = v_now
  where requester_user_id = v_request.requester_user_id
    and status = 'pending'
    and id <> v_request.id;

  for v_expired_invite in
    update public.club_invites
    set status = 'expired',
        resolved_at = v_now,
        resolved_by_user_id = p_actor_user_id,
        resolved_by_membership_id = v_captain.id
    where target_user_id = v_request.requester_user_id
      and status = 'pending'
    returning *
  loop
    v_expired_invite_ids := array_append(v_expired_invite_ids, v_expired_invite.id);

    perform public.clubline_log_event(
      v_expired_invite.club_id,
      null,
      p_actor_user_id,
      v_request.requester_user_id,
      'invite_expired',
      jsonb_build_object(
        'invite_id', v_expired_invite.id,
        'reason', 'join_request_approved',
        'join_request_id', v_request.id,
        'membership_id', v_membership.id
      )
    );
  end loop;

  if cardinality(v_expired_invite_ids) > 0 then
    update public.app_notifications
    set read_at = coalesce(read_at, v_now)
    where recipient_user_id = v_request.requester_user_id
      and notification_type = 'club_invite_received'
      and related_invite_id = any(v_expired_invite_ids);
  end if;

  perform public.clubline_log_event(
    v_request.club_id,
    v_membership.id,
    p_actor_user_id,
    v_request.requester_user_id,
    'join_approved',
    jsonb_build_object(
      'join_request_id', v_request.id,
      'membership_id', v_membership.id,
      'player_id', v_player_id
    )
  );

  return jsonb_build_object(
    'membership_id', v_membership.id,
    'player_id', v_player_id
  );
end;
$$;

alter table public.club_invites enable row level security;
alter table public.app_notifications enable row level security;

drop policy if exists club_invites_select_target_or_manager on public.club_invites;
create policy club_invites_select_target_or_manager
  on public.club_invites
  for select
  to authenticated
  using (
    target_user_id = auth.uid()
    or public.clubline_current_user_can_manage_invites_for_club(club_id)
  );

drop policy if exists app_notifications_select_own on public.app_notifications;
create policy app_notifications_select_own
  on public.app_notifications
  for select
  to authenticated
  using (recipient_user_id = auth.uid());

grant select, insert, update, delete
  on table public.club_invites,
           public.app_notifications
  to service_role;

grant usage, select on all sequences in schema public
  to service_role;

revoke all
  on table public.club_invites,
           public.app_notifications
  from anon, authenticated;

grant select
  on table public.club_invites,
           public.app_notifications
  to authenticated;

revoke all on function public.clubline_current_user_can_manage_invites_for_club(bigint)
  from public, anon, authenticated;
grant execute on function public.clubline_current_user_can_manage_invites_for_club(bigint)
  to authenticated, service_role;

revoke all on function public.clubline_lock_user_membership_flow(uuid)
  from public, anon, authenticated;
grant execute on function public.clubline_lock_user_membership_flow(uuid)
  to service_role;

revoke all on function public.clubline_create_notification(
  uuid, bigint, text, text, text, jsonb, bigint, text
)
  from public, anon, authenticated;
grant execute on function public.clubline_create_notification(
  uuid, bigint, text, text, text, jsonb, bigint, text
)
  to service_role;

revoke all on function public.clubline_create_club_invite(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.clubline_create_club_invite(uuid, uuid)
  to service_role;

revoke all on function public.clubline_revoke_club_invite(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.clubline_revoke_club_invite(uuid, bigint)
  to service_role;

revoke all on function public.clubline_accept_club_invite(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.clubline_accept_club_invite(uuid, bigint)
  to service_role;

revoke all on function public.clubline_decline_club_invite(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.clubline_decline_club_invite(uuid, bigint)
  to service_role;

grant execute on function public.clubline_create_club(
  uuid, text, text, text, text, text, integer, text, text, text, text
)
  to service_role;
grant execute on function public.clubline_request_join_club(
  uuid, text, bigint, text, text, integer, text
)
  to service_role;
grant execute on function public.clubline_approve_join_request(uuid, bigint)
  to service_role;

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    begin
      alter publication supabase_realtime add table public.club_invites;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.app_notifications;
    exception
      when duplicate_object then null;
    end;
  end if;
end
$$;

alter table public.club_invites replica identity full;
alter table public.app_notifications replica identity full;

commit;
