begin;

create index if not exists memberships_user_status_created_idx
  on public.memberships (auth_user_id, status, created_at desc);

create index if not exists memberships_club_role_status_idx
  on public.memberships (club_id, role, status, created_at desc);

create index if not exists join_requests_requester_status_created_idx
  on public.join_requests (requester_user_id, status, created_at desc);

create index if not exists join_requests_pending_club_created_idx
  on public.join_requests (club_id, created_at desc)
  where status = 'pending';

create index if not exists leave_requests_requester_status_created_idx
  on public.leave_requests (requested_by_user_id, status, created_at desc);

create index if not exists leave_requests_pending_club_created_idx
  on public.leave_requests (club_id, created_at desc)
  where status = 'pending';

create index if not exists clubs_normalized_name_prefix_idx
  on public.clubs (normalized_name text_pattern_ops);

create index if not exists clubs_slug_prefix_idx
  on public.clubs (slug text_pattern_ops);

create index if not exists player_profiles_membership_active_idx
  on public.player_profiles (membership_id)
  where archived_at is null;

create index if not exists player_profiles_club_auth_active_idx
  on public.player_profiles (club_id, auth_user_id)
  where archived_at is null;

create table if not exists public.club_membership_events (
  id bigint generated by default as identity primary key,
  club_id bigint
    references public.clubs(id) on delete set null,
  membership_id bigint
    references public.memberships(id) on delete set null,
  actor_user_id uuid
    references auth.users(id) on delete set null,
  target_user_id uuid
    references auth.users(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint club_membership_events_payload_is_object_check
    check (jsonb_typeof(payload) = 'object')
);

create index if not exists club_membership_events_club_created_idx
  on public.club_membership_events (club_id, created_at desc);

create index if not exists club_membership_events_target_created_idx
  on public.club_membership_events (target_user_id, created_at desc);

create or replace function public.clubline_normalize_text(value text)
returns text
language sql
immutable
as $$
  select nullif(regexp_replace(btrim(coalesce(value, '')), '\s+', ' ', 'g'), '')
$$;

create or replace function public.clubline_normalize_email(value text)
returns text
language sql
immutable
as $$
  select nullif(lower(btrim(coalesce(value, ''))), '')
$$;

create or replace function public.clubline_slugify(value text)
returns text
language sql
immutable
as $$
  select case
    when nullif(
      regexp_replace(
        regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '-', 'g'),
        '(^-+|-+$)',
        '',
        'g'
      ),
      ''
    ) is null then 'club'
    else regexp_replace(
      regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '-', 'g'),
      '(^-+|-+$)',
      '',
      'g'
    )
  end
$$;

create or replace function public.clubline_current_auth_user_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid()
$$;

create or replace function public.clubline_current_membership_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select membership.id
  from public.memberships as membership
  where membership.auth_user_id = auth.uid()
    and membership.status = 'active'
  order by membership.created_at desc
  limit 1
$$;

create or replace function public.clubline_current_club_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select membership.club_id
  from public.memberships as membership
  where membership.auth_user_id = auth.uid()
    and membership.status = 'active'
  order by membership.created_at desc
  limit 1
$$;

create or replace function public.clubline_current_user_is_captain()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.memberships as membership
    where membership.auth_user_id = auth.uid()
      and membership.status = 'active'
      and membership.role = 'captain'
  )
$$;

create or replace function public.clubline_current_user_is_captain_for_club(target_club_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.memberships as membership
    where membership.auth_user_id = auth.uid()
      and membership.club_id = target_club_id
      and membership.status = 'active'
      and membership.role = 'captain'
  )
$$;

create or replace function public.clubline_current_account_email()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select public.clubline_normalize_email(auth.jwt()->>'email')
$$;

create or replace function public.clubline_current_player_profile_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select player.id
  from public.player_profiles as player
  where player.archived_at is null
    and player.club_id = public.clubline_current_club_id()
    and (
      player.auth_user_id = auth.uid()
      or (
        player.account_email is not null
        and player.account_email = public.clubline_current_account_email()
      )
    )
  order by player.created_at desc nulls last, player.id desc
  limit 1
$$;

create or replace function public.clubline_current_user_can_manage_attendance_for_club(target_club_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.memberships as membership
    left join public.club_permission_settings as permissions
      on permissions.club_id = membership.club_id
    where membership.auth_user_id = auth.uid()
      and membership.club_id = target_club_id
      and membership.status = 'active'
      and (
        membership.role = 'captain'
        or (
          membership.role = 'vice_captain'
          and coalesce(permissions.vice_manage_attendance, false)
        )
      )
  )
$$;

create or replace function public.clubline_log_event(
  p_club_id bigint,
  p_membership_id bigint,
  p_actor_user_id uuid,
  p_target_user_id uuid,
  p_event_type text,
  p_payload jsonb default '{}'::jsonb
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.club_membership_events (
    club_id,
    membership_id,
    actor_user_id,
    target_user_id,
    event_type,
    payload
  )
  values (
    p_club_id,
    p_membership_id,
    p_actor_user_id,
    p_target_user_id,
    p_event_type,
    coalesce(p_payload, '{}'::jsonb)
  )
$$;

create or replace function public.clubline_next_club_slug(base_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_base text := public.clubline_slugify(base_name);
  candidate text := normalized_base;
  suffix integer := 2;
begin
  while exists (
    select 1
    from public.clubs
    where slug = candidate
  ) loop
    candidate := normalized_base || '-' || suffix::text;
    suffix := suffix + 1;
  end loop;

  return candidate;
end;
$$;

create or replace function public.clubline_attach_player_profile(
  p_membership_id bigint,
  p_auth_user_id uuid,
  p_account_email text,
  p_nome text,
  p_cognome text,
  p_id_console text,
  p_shirt_number integer,
  p_primary_role text,
  p_team_role text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_membership public.memberships%rowtype;
  v_player public.player_profiles%rowtype;
  v_email text := public.clubline_normalize_email(p_account_email);
  v_console text := public.clubline_normalize_text(p_id_console);
  v_nome text := coalesce(public.clubline_normalize_text(p_nome), 'Clubline');
  v_cognome text := coalesce(public.clubline_normalize_text(p_cognome), 'Player');
  v_team_role text := coalesce(public.clubline_normalize_text(p_team_role), 'player');
begin
  select *
    into v_membership
  from public.memberships
  where id = p_membership_id
  for update;

  if not found or v_membership.status <> 'active' then
    raise exception using errcode = 'P0001', message = 'Membership attiva non trovata';
  end if;

  select *
    into v_player
  from public.player_profiles
  where membership_id = p_membership_id
    and archived_at is null
  for update;

  if not found and p_auth_user_id is not null then
    select *
      into v_player
    from public.player_profiles
    where auth_user_id = p_auth_user_id
      and archived_at is null
    order by created_at asc
    limit 1
    for update;
  end if;

  if not found and v_email is not null then
    select *
      into v_player
    from public.player_profiles
    where lower(account_email) = v_email
      and archived_at is null
    order by created_at asc
    limit 1
    for update;
  end if;

  if not found and v_console is not null then
    select *
      into v_player
    from public.player_profiles
    where id_console = v_console
      and archived_at is null
    order by created_at asc
    limit 1
    for update;
  end if;

  if found and v_player.club_id is not null and v_player.club_id <> v_membership.club_id then
    raise exception using errcode = 'P0001', message = 'Il giocatore risulta gia attivo in un altro club';
  end if;

  if found then
    update public.player_profiles
    set club_id = v_membership.club_id,
        membership_id = v_membership.id,
        auth_user_id = coalesce(p_auth_user_id, auth_user_id),
        account_email = coalesce(v_email, account_email),
        nome = v_nome,
        cognome = v_cognome,
        shirt_number = coalesce(p_shirt_number, shirt_number),
        primary_role = coalesce(public.clubline_normalize_text(p_primary_role), primary_role),
        id_console = coalesce(v_console, id_console),
        team_role = v_team_role,
        archived_at = null
    where id = v_player.id
    returning * into v_player;

    return v_player.id;
  end if;

  insert into public.player_profiles (
    club_id,
    membership_id,
    nome,
    cognome,
    auth_user_id,
    account_email,
    shirt_number,
    primary_role,
    secondary_role,
    secondary_roles,
    id_console,
    team_role
  )
  values (
    v_membership.club_id,
    v_membership.id,
    v_nome,
    v_cognome,
    p_auth_user_id,
    v_email,
    p_shirt_number,
    public.clubline_normalize_text(p_primary_role),
    null,
    '{}'::text[],
    v_console,
    v_team_role
  )
  returning * into v_player;

  return v_player.id;
end;
$$;

create or replace function public.clubline_create_club(
  p_actor_user_id uuid,
  p_actor_email text,
  p_name text,
  p_owner_nome text,
  p_owner_cognome text,
  p_owner_id_console text,
  p_owner_shirt_number integer default null,
  p_owner_primary_role text default null,
  p_primary_color text default null,
  p_accent_color text default null,
  p_surface_color text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := public.clubline_normalize_text(p_name);
  v_owner_nome text := public.clubline_normalize_text(p_owner_nome);
  v_owner_cognome text := public.clubline_normalize_text(p_owner_cognome);
  v_owner_console text := public.clubline_normalize_text(p_owner_id_console);
  v_slug text;
  v_club public.clubs%rowtype;
  v_membership public.memberships%rowtype;
  v_player_id bigint;
begin
  if v_name is null then
    raise exception using errcode = '22023', message = 'Inserisci un nome club valido';
  end if;
  if v_owner_nome is null or v_owner_cognome is null or v_owner_console is null then
    raise exception using errcode = '22023', message = 'Inserisci nome, cognome e ID console del capitano';
  end if;

  perform 1
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Appartieni gia a un club attivo';
  end if;

  perform 1
  from public.join_requests
  where requester_user_id = p_actor_user_id
    and status = 'pending'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Hai gia una richiesta di ingresso pendente';
  end if;

  v_slug := public.clubline_next_club_slug(v_name);

  insert into public.clubs (
    name,
    normalized_name,
    slug,
    primary_color,
    accent_color,
    surface_color,
    created_by_user_id
  )
  values (
    v_name,
    lower(v_name),
    v_slug,
    coalesce(public.clubline_normalize_text(p_primary_color), '#1F2937'),
    coalesce(public.clubline_normalize_text(p_accent_color), '#0F766E'),
    coalesce(public.clubline_normalize_text(p_surface_color), '#0F172A'),
    p_actor_user_id
  )
  returning * into v_club;

  insert into public.club_settings (
    club_id,
    additional_links
  )
  values (
    v_club.id,
    '[]'::jsonb
  )
  on conflict (club_id) do nothing;

  insert into public.club_permission_settings (
    club_id,
    vice_manage_players,
    vice_manage_lineups,
    vice_manage_streams,
    vice_manage_attendance,
    vice_manage_team_info
  )
  values (
    v_club.id,
    false,
    false,
    false,
    false,
    false
  )
  on conflict (club_id) do nothing;

  insert into public.memberships (
    club_id,
    auth_user_id,
    role,
    status
  )
  values (
    v_club.id,
    p_actor_user_id,
    'captain',
    'active'
  )
  returning * into v_membership;

  v_player_id := public.clubline_attach_player_profile(
    v_membership.id,
    p_actor_user_id,
    p_actor_email,
    v_owner_nome,
    v_owner_cognome,
    v_owner_console,
    p_owner_shirt_number,
    p_owner_primary_role,
    'captain'
  );

  perform public.clubline_log_event(
    v_club.id,
    v_membership.id,
    p_actor_user_id,
    p_actor_user_id,
    'club_created',
    jsonb_build_object(
      'club_id', v_club.id,
      'membership_id', v_membership.id,
      'player_id', v_player_id
    )
  );

  return jsonb_build_object(
    'club_id', v_club.id,
    'membership_id', v_membership.id,
    'player_id', v_player_id
  );
end;
$$;

create or replace function public.clubline_request_join_club(
  p_actor_user_id uuid,
  p_actor_email text,
  p_club_id bigint,
  p_requested_nome text,
  p_requested_cognome text,
  p_requested_shirt_number integer default null,
  p_requested_primary_role text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nome text := coalesce(public.clubline_normalize_text(p_requested_nome), 'Clubline');
  v_cognome text := coalesce(public.clubline_normalize_text(p_requested_cognome), 'Player');
  v_request public.join_requests%rowtype;
begin
  perform 1
  from public.clubs
  where id = p_club_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Club non trovato';
  end if;

  perform 1
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Appartieni gia a un club attivo';
  end if;

  perform 1
  from public.join_requests
  where requester_user_id = p_actor_user_id
    and status = 'pending'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Hai gia una richiesta di ingresso pendente';
  end if;

  insert into public.join_requests (
    club_id,
    requester_user_id,
    requester_email,
    requested_nome,
    requested_cognome,
    requested_shirt_number,
    requested_primary_role,
    status
  )
  values (
    p_club_id,
    p_actor_user_id,
    public.clubline_normalize_email(p_actor_email),
    v_nome,
    v_cognome,
    p_requested_shirt_number,
    public.clubline_normalize_text(p_requested_primary_role),
    'pending'
  )
  returning * into v_request;

  perform public.clubline_log_event(
    v_request.club_id,
    null,
    p_actor_user_id,
    p_actor_user_id,
    'join_requested',
    jsonb_build_object('join_request_id', v_request.id)
  );

  return jsonb_build_object('join_request_id', v_request.id);
end;
$$;

create or replace function public.clubline_approve_join_request(
  p_actor_user_id uuid,
  p_join_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_captain public.memberships%rowtype;
  v_request public.join_requests%rowtype;
  v_membership public.memberships%rowtype;
  v_player_id bigint;
begin
  select *
    into v_request
  from public.join_requests
  where id = p_join_request_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Richiesta di ingresso non trovata';
  end if;
  if v_request.status <> 'pending' then
    raise exception using errcode = 'P0001', message = 'Questa richiesta di ingresso e gia stata gestita';
  end if;

  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and club_id = v_request.club_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano del club puo approvare la richiesta';
  end if;

  perform 1
  from public.memberships
  where auth_user_id = v_request.requester_user_id
    and status = 'active'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'L utente appartiene gia a un club';
  end if;

  insert into public.memberships (
    club_id,
    auth_user_id,
    role,
    status
  )
  values (
    v_request.club_id,
    v_request.requester_user_id,
    'player',
    'active'
  )
  returning * into v_membership;

  v_player_id := public.clubline_attach_player_profile(
    v_membership.id,
    v_request.requester_user_id,
    v_request.requester_email,
    v_request.requested_nome,
    v_request.requested_cognome,
    null,
    v_request.requested_shirt_number,
    v_request.requested_primary_role,
    'player'
  );

  update public.join_requests
  set status = 'approved',
      decided_by_membership_id = v_captain.id,
      decided_at = timezone('utc', now())
  where id = v_request.id;

  update public.join_requests
  set status = 'expired',
      decided_by_membership_id = v_captain.id,
      decided_at = timezone('utc', now())
  where requester_user_id = v_request.requester_user_id
    and status = 'pending'
    and id <> v_request.id;

  perform public.clubline_log_event(
    v_request.club_id,
    v_membership.id,
    p_actor_user_id,
    v_request.requester_user_id,
    'join_approved',
    jsonb_build_object(
      'join_request_id', v_request.id,
      'membership_id', v_membership.id,
      'player_id', v_player_id
    )
  );

  return jsonb_build_object(
    'membership_id', v_membership.id,
    'player_id', v_player_id
  );
end;
$$;

create or replace function public.clubline_reject_join_request(
  p_actor_user_id uuid,
  p_join_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_captain public.memberships%rowtype;
  v_request public.join_requests%rowtype;
begin
  select *
    into v_request
  from public.join_requests
  where id = p_join_request_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Richiesta di ingresso non trovata';
  end if;
  if v_request.status <> 'pending' then
    raise exception using errcode = 'P0001', message = 'Questa richiesta di ingresso e gia stata gestita';
  end if;

  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and club_id = v_request.club_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano del club puo rifiutare la richiesta';
  end if;

  update public.join_requests
  set status = 'rejected',
      decided_by_membership_id = v_captain.id,
      decided_at = timezone('utc', now())
  where id = v_request.id;

  perform public.clubline_log_event(
    v_request.club_id,
    null,
    p_actor_user_id,
    v_request.requester_user_id,
    'join_rejected',
    jsonb_build_object('join_request_id', v_request.id)
  );

  return jsonb_build_object('join_request_id', v_request.id, 'status', 'rejected');
end;
$$;

create or replace function public.clubline_request_leave_club(
  p_actor_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_membership public.memberships%rowtype;
  v_active_member_count integer;
  v_request public.leave_requests%rowtype;
begin
  select *
    into v_membership
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Devi appartenere a un club per usare questo flusso';
  end if;

  if v_membership.role = 'captain' then
    select count(*)
      into v_active_member_count
    from public.memberships
    where club_id = v_membership.club_id
      and status = 'active';

    if v_active_member_count > 1 then
      raise exception using errcode = 'P0001', message = 'Trasferisci prima il ruolo di capitano';
    end if;

    raise exception using errcode = 'P0001', message = 'Se sei l unico membro del club puoi eliminarlo direttamente';
  end if;

  perform 1
  from public.leave_requests
  where membership_id = v_membership.id
    and status = 'pending'
  for update;

  if found then
    raise exception using errcode = 'P0001', message = 'Esiste gia una richiesta di uscita pendente';
  end if;

  insert into public.leave_requests (
    club_id,
    membership_id,
    requested_by_user_id,
    status
  )
  values (
    v_membership.club_id,
    v_membership.id,
    p_actor_user_id,
    'pending'
  )
  returning * into v_request;

  perform public.clubline_log_event(
    v_membership.club_id,
    v_membership.id,
    p_actor_user_id,
    p_actor_user_id,
    'leave_requested',
    jsonb_build_object('leave_request_id', v_request.id)
  );

  return jsonb_build_object('leave_request_id', v_request.id);
end;
$$;

create or replace function public.clubline_approve_leave_request(
  p_actor_user_id uuid,
  p_leave_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.leave_requests%rowtype;
  v_captain public.memberships%rowtype;
  v_target public.memberships%rowtype;
  v_now timestamptz := timezone('utc', now());
begin
  select *
    into v_request
  from public.leave_requests
  where id = p_leave_request_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Richiesta di uscita non trovata';
  end if;
  if v_request.status <> 'pending' then
    raise exception using errcode = 'P0001', message = 'Questa richiesta di uscita e gia stata gestita';
  end if;

  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and club_id = v_request.club_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano del club puo approvare l uscita';
  end if;

  select *
    into v_target
  from public.memberships
  where id = v_request.membership_id
  for update;

  if not found or v_target.status <> 'active' then
    raise exception using errcode = 'P0001', message = 'La membership di uscita non e piu attiva';
  end if;
  if v_target.role = 'captain' then
    raise exception using errcode = 'P0001', message = 'Il capitano deve trasferire il ruolo prima di uscire';
  end if;

  update public.leave_requests
  set status = 'approved',
      decided_by_membership_id = v_captain.id,
      decided_at = v_now
  where id = v_request.id;

  update public.memberships
  set status = 'left',
      left_at = v_now
  where id = v_target.id;

  perform public.clubline_log_event(
    v_request.club_id,
    v_target.id,
    p_actor_user_id,
    v_target.auth_user_id,
    'leave_approved',
    jsonb_build_object('leave_request_id', v_request.id)
  );

  return jsonb_build_object('membership_id', v_target.id, 'status', 'left');
end;
$$;

create or replace function public.clubline_reject_leave_request(
  p_actor_user_id uuid,
  p_leave_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.leave_requests%rowtype;
  v_captain public.memberships%rowtype;
begin
  select *
    into v_request
  from public.leave_requests
  where id = p_leave_request_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Richiesta di uscita non trovata';
  end if;
  if v_request.status <> 'pending' then
    raise exception using errcode = 'P0001', message = 'Questa richiesta di uscita e gia stata gestita';
  end if;

  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and club_id = v_request.club_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano del club puo rifiutare l uscita';
  end if;

  update public.leave_requests
  set status = 'rejected',
      decided_by_membership_id = v_captain.id,
      decided_at = timezone('utc', now())
  where id = v_request.id;

  perform public.clubline_log_event(
    v_request.club_id,
    v_request.membership_id,
    p_actor_user_id,
    v_request.requested_by_user_id,
    'leave_rejected',
    jsonb_build_object('leave_request_id', v_request.id)
  );

  return jsonb_build_object('leave_request_id', v_request.id, 'status', 'rejected');
end;
$$;

create or replace function public.clubline_transfer_captain_role(
  p_actor_user_id uuid,
  p_target_membership_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_captain public.memberships%rowtype;
  v_target public.memberships%rowtype;
begin
  select *
    into v_target
  from public.memberships
  where id = p_target_membership_id
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Membership di destinazione non trovata';
  end if;

  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and club_id = v_target.club_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano del club puo trasferire il ruolo';
  end if;
  if v_captain.id = v_target.id then
    raise exception using errcode = 'P0001', message = 'Seleziona un altro membro per il trasferimento';
  end if;
  if v_target.status <> 'active' then
    raise exception using errcode = 'P0001', message = 'Il nuovo capitano deve essere un membro attivo';
  end if;

  update public.memberships
  set role = 'player'
  where id = v_captain.id;

  update public.memberships
  set role = 'captain'
  where id = v_target.id;

  update public.player_profiles
  set team_role = 'player'
  where membership_id = v_captain.id
    and archived_at is null;

  update public.player_profiles
  set team_role = 'captain'
  where membership_id = v_target.id
    and archived_at is null;

  perform public.clubline_log_event(
    v_captain.club_id,
    v_target.id,
    p_actor_user_id,
    v_target.auth_user_id,
    'captain_transferred',
    jsonb_build_object(
      'previous_captain_membership_id', v_captain.id,
      'new_captain_membership_id', v_target.id
    )
  );

  return jsonb_build_object(
    'previous_captain_membership_id', v_captain.id,
    'new_captain_membership_id', v_target.id
  );
end;
$$;

create or replace function public.clubline_delete_club_if_valid(
  p_actor_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_captain public.memberships%rowtype;
  v_active_member_count integer;
  v_club_id bigint;
begin
  select *
    into v_captain
  from public.memberships
  where auth_user_id = p_actor_user_id
    and status = 'active'
    and role = 'captain'
  for update;

  if not found then
    raise exception using errcode = '42501', message = 'Solo il capitano puo eliminare il club corrente';
  end if;

  select count(*)
    into v_active_member_count
  from public.memberships
  where club_id = v_captain.club_id
    and status = 'active';

  if v_active_member_count <> 1 then
    raise exception using errcode = 'P0001', message = 'Puoi eliminare il club solo se sei l unico membro attivo';
  end if;

  v_club_id := v_captain.club_id;

  perform public.clubline_log_event(
    v_captain.club_id,
    v_captain.id,
    p_actor_user_id,
    p_actor_user_id,
    'club_deleted',
    jsonb_build_object('club_id', v_captain.club_id)
  );

  delete from public.clubs
  where id = v_captain.club_id;

  return jsonb_build_object('club_id', v_club_id, 'deleted', true);
end;
$$;

alter table public.lineup_players
  add column if not exists club_id bigint references public.clubs(id) on delete cascade;

update public.lineup_players as assignment
set club_id = lineup.club_id
from public.lineups as lineup
where lineup.id = assignment.lineup_id
  and assignment.club_id is distinct from lineup.club_id;

do $$
begin
  if exists (
    select 1
    from public.lineup_players
    where club_id is null
  ) then
    raise exception using errcode = 'P0001', message = 'Impossibile allineare lineup_players.club_id: esistono righe senza club associato';
  end if;
end
$$;

alter table public.lineup_players
  alter column club_id set not null;

create index if not exists lineup_players_club_lineup_idx
  on public.lineup_players (club_id, lineup_id);

create or replace function public.clubline_sync_lineup_player_club_id()
returns trigger
language plpgsql
as $$
declare
  v_lineup_club_id bigint;
  v_player_club_id bigint;
  v_player_archived_at timestamptz;
begin
  select club_id
    into v_lineup_club_id
  from public.lineups
  where id = new.lineup_id;

  if v_lineup_club_id is null then
    raise exception using errcode = '23503', message = 'La formazione selezionata non appartiene a nessun club valido';
  end if;

  select club_id, archived_at
    into v_player_club_id, v_player_archived_at
  from public.player_profiles
  where id = new.player_id;

  if v_player_club_id is null then
    raise exception using errcode = '23503', message = 'Il giocatore selezionato non appartiene a nessun club valido';
  end if;

  if v_player_archived_at is not null then
    raise exception using errcode = 'P0001', message = 'Non puoi assegnare alla formazione un giocatore archiviato';
  end if;

  if v_player_club_id is distinct from v_lineup_club_id then
    raise exception using errcode = 'P0001', message = 'Il giocatore non appartiene al club della formazione';
  end if;

  new.club_id := v_lineup_club_id;
  return new;
end;
$$;

drop trigger if exists lineup_players_sync_club_id on public.lineup_players;

create trigger lineup_players_sync_club_id
before insert or update on public.lineup_players
for each row
execute function public.clubline_sync_lineup_player_club_id();

alter table public.clubs enable row level security;
alter table public.club_settings enable row level security;
alter table public.club_permission_settings enable row level security;
alter table public.memberships enable row level security;
alter table public.join_requests enable row level security;
alter table public.leave_requests enable row level security;
alter table public.club_membership_events enable row level security;
alter table public.stream_links enable row level security;
alter table public.lineups enable row level security;
alter table public.lineup_players enable row level security;
alter table public.attendance_weeks enable row level security;
alter table public.attendance_entries enable row level security;

drop policy if exists team_settings_select_dev on public.team_settings;
drop policy if exists team_settings_insert_dev on public.team_settings;
drop policy if exists team_settings_update_dev on public.team_settings;
drop policy if exists team_settings_delete_dev on public.team_settings;

drop policy if exists team_permission_settings_select_dev on public.team_permission_settings;
drop policy if exists team_permission_settings_insert_dev on public.team_permission_settings;
drop policy if exists team_permission_settings_update_dev on public.team_permission_settings;
drop policy if exists team_permission_settings_delete_dev on public.team_permission_settings;

drop policy if exists clubs_select_member_or_requester on public.clubs;
create policy clubs_select_member_or_requester
  on public.clubs
  for select
  to authenticated
  using (
    id = public.clubline_current_club_id()
    or exists (
      select 1
      from public.join_requests as request
      where request.club_id = clubs.id
        and request.requester_user_id = auth.uid()
        and request.status = 'pending'
    )
  );

drop policy if exists club_settings_select_member on public.club_settings;
create policy club_settings_select_member
  on public.club_settings
  for select
  to authenticated
  using (club_id = public.clubline_current_club_id());

drop policy if exists club_permission_settings_select_member on public.club_permission_settings;
create policy club_permission_settings_select_member
  on public.club_permission_settings
  for select
  to authenticated
  using (club_id = public.clubline_current_club_id());

drop policy if exists memberships_select_same_club_or_self on public.memberships;
create policy memberships_select_same_club_or_self
  on public.memberships
  for select
  to authenticated
  using (
    auth_user_id = auth.uid()
    or club_id = public.clubline_current_club_id()
  );

drop policy if exists join_requests_select_own_or_captain on public.join_requests;
create policy join_requests_select_own_or_captain
  on public.join_requests
  for select
  to authenticated
  using (
    requester_user_id = auth.uid()
    or (
      club_id = public.clubline_current_club_id()
      and public.clubline_current_user_is_captain_for_club(club_id)
    )
  );

drop policy if exists leave_requests_select_own_or_captain on public.leave_requests;
create policy leave_requests_select_own_or_captain
  on public.leave_requests
  for select
  to authenticated
  using (
    requested_by_user_id = auth.uid()
    or membership_id = public.clubline_current_membership_id()
    or (
      club_id = public.clubline_current_club_id()
      and public.clubline_current_user_is_captain_for_club(club_id)
    )
  );

drop policy if exists club_membership_events_select_own_or_captain on public.club_membership_events;
create policy club_membership_events_select_own_or_captain
  on public.club_membership_events
  for select
  to authenticated
  using (
    target_user_id = auth.uid()
    or (
      club_id = public.clubline_current_club_id()
      and public.clubline_current_user_is_captain_for_club(club_id)
    )
  );

drop policy if exists player_profiles_select_authenticated on public.player_profiles;
drop policy if exists player_profiles_insert_authenticated on public.player_profiles;
drop policy if exists player_profiles_update_authenticated on public.player_profiles;
drop policy if exists player_profiles_delete_authenticated on public.player_profiles;

create policy player_profiles_select_authenticated
  on public.player_profiles
  for select
  to authenticated
  using (
    auth_user_id = auth.uid()
    or (
      archived_at is null
      and club_id = public.clubline_current_club_id()
    )
  );

drop policy if exists stream_links_select_member on public.stream_links;
drop policy if exists stream_links_select_dev on public.stream_links;
drop policy if exists stream_links_insert_dev on public.stream_links;
drop policy if exists stream_links_update_dev on public.stream_links;
drop policy if exists stream_links_delete_dev on public.stream_links;
create policy stream_links_select_member
  on public.stream_links
  for select
  to authenticated
  using (club_id = public.clubline_current_club_id());

drop policy if exists lineups_select_member on public.lineups;
drop policy if exists lineups_select_dev on public.lineups;
drop policy if exists lineups_insert_dev on public.lineups;
drop policy if exists lineups_update_dev on public.lineups;
drop policy if exists lineups_delete_dev on public.lineups;
create policy lineups_select_member
  on public.lineups
  for select
  to authenticated
  using (club_id = public.clubline_current_club_id());

drop policy if exists lineup_players_select_member on public.lineup_players;
drop policy if exists lineup_players_select_dev on public.lineup_players;
drop policy if exists lineup_players_insert_dev on public.lineup_players;
drop policy if exists lineup_players_update_dev on public.lineup_players;
drop policy if exists lineup_players_delete_dev on public.lineup_players;
create policy lineup_players_select_member
  on public.lineup_players
  for select
  to authenticated
  using (club_id = public.clubline_current_club_id());

drop policy if exists attendance_weeks_select_member on public.attendance_weeks;
drop policy if exists attendance_weeks_select_dev on public.attendance_weeks;
drop policy if exists attendance_weeks_insert_dev on public.attendance_weeks;
drop policy if exists attendance_weeks_update_dev on public.attendance_weeks;
drop policy if exists attendance_weeks_delete_dev on public.attendance_weeks;
create policy attendance_weeks_select_member
  on public.attendance_weeks
  for select
  to authenticated
  using (club_id = public.clubline_current_club_id());

drop policy if exists attendance_entries_select_member_or_manager on public.attendance_entries;
drop policy if exists attendance_entries_select_dev on public.attendance_entries;
drop policy if exists attendance_entries_insert_dev on public.attendance_entries;
drop policy if exists attendance_entries_update_dev on public.attendance_entries;
drop policy if exists attendance_entries_delete_dev on public.attendance_entries;
create policy attendance_entries_select_member_or_manager
  on public.attendance_entries
  for select
  to authenticated
  using (
    (
      club_id = public.clubline_current_club_id()
      and public.clubline_current_user_can_manage_attendance_for_club(club_id)
    )
    or player_id = public.clubline_current_player_profile_id()
  );

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    begin
      alter publication supabase_realtime add table public.clubs;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.club_settings;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.club_permission_settings;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.memberships;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.join_requests;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.leave_requests;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.player_profiles;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.stream_links;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.lineups;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.lineup_players;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.attendance_weeks;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.attendance_entries;
    exception
      when duplicate_object then null;
    end;
    begin
      alter publication supabase_realtime add table public.club_membership_events;
    exception
      when duplicate_object then null;
    end;
  end if;
end
$$;

alter table public.clubs replica identity full;
alter table public.club_settings replica identity full;
alter table public.club_permission_settings replica identity full;
alter table public.memberships replica identity full;
alter table public.join_requests replica identity full;
alter table public.leave_requests replica identity full;
alter table public.player_profiles replica identity full;
alter table public.stream_links replica identity full;
alter table public.lineups replica identity full;
alter table public.lineup_players replica identity full;
alter table public.attendance_weeks replica identity full;
alter table public.attendance_entries replica identity full;
alter table public.club_membership_events replica identity full;

grant execute on function public.clubline_create_club(
  uuid, text, text, text, text, text, integer, text, text, text, text
) to service_role;
grant execute on function public.clubline_request_join_club(
  uuid, text, bigint, text, text, integer, text
) to service_role;
grant execute on function public.clubline_approve_join_request(uuid, bigint) to service_role;
grant execute on function public.clubline_reject_join_request(uuid, bigint) to service_role;
grant execute on function public.clubline_request_leave_club(uuid) to service_role;
grant execute on function public.clubline_approve_leave_request(uuid, bigint) to service_role;
grant execute on function public.clubline_reject_leave_request(uuid, bigint) to service_role;
grant execute on function public.clubline_transfer_captain_role(uuid, bigint) to service_role;
grant execute on function public.clubline_delete_club_if_valid(uuid) to service_role;

commit;
