begin;

create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text not null,
  slug text not null,
  logo_url text,
  logo_storage_path text,
  primary_color text,
  accent_color text,
  surface_color text,
  created_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint clubs_name_not_blank check (char_length(btrim(name)) > 0),
  constraint clubs_normalized_name_not_blank check (char_length(btrim(normalized_name)) > 0),
  constraint clubs_slug_not_blank check (char_length(btrim(slug)) > 0)
);

create unique index if not exists clubs_normalized_name_unique
  on public.clubs (normalized_name);

create unique index if not exists clubs_slug_unique
  on public.clubs (slug);

create table if not exists public.club_settings (
  club_id bigint primary key
    references public.clubs(id) on delete cascade,
  website_url text,
  youtube_url text,
  discord_url text,
  facebook_url text,
  instagram_url text,
  twitch_url text,
  tiktok_url text,
  additional_links jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint club_settings_additional_links_is_array_check
    check (jsonb_typeof(additional_links) = 'array')
);

create table if not exists public.club_permission_settings (
  club_id bigint primary key
    references public.clubs(id) on delete cascade,
  vice_manage_players boolean not null default false,
  vice_manage_lineups boolean not null default false,
  vice_manage_streams boolean not null default false,
  vice_manage_attendance boolean not null default false,
  vice_manage_team_info boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  club_id bigint not null
    references public.clubs(id) on delete cascade,
  auth_user_id uuid not null
    references auth.users(id) on delete cascade,
  role text not null default 'player',
  status text not null default 'active',
  left_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint memberships_role_check
    check (role in ('player', 'vice_captain', 'captain')),
  constraint memberships_status_check
    check (status in ('active', 'left'))
);

create unique index if not exists memberships_user_active_unique
  on public.memberships (auth_user_id)
  where status = 'active';

create unique index if not exists memberships_club_captain_unique
  on public.memberships (club_id)
  where status = 'active' and role = 'captain';

create index if not exists memberships_club_status_idx
  on public.memberships (club_id, status);

create table if not exists public.join_requests (
  id bigint generated by default as identity primary key,
  club_id bigint not null
    references public.clubs(id) on delete cascade,
  requester_user_id uuid not null
    references auth.users(id) on delete cascade,
  requester_email text,
  requested_nome text not null,
  requested_cognome text not null,
  requested_shirt_number integer,
  requested_primary_role text,
  status text not null default 'pending',
  decided_by_membership_id bigint
    references public.memberships(id) on delete set null,
  decided_at timestamptz,
  cancelled_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint join_requests_status_check
    check (status in ('pending', 'approved', 'rejected', 'cancelled', 'expired'))
);

alter table public.join_requests
  drop constraint if exists join_requests_requested_nome_not_blank;

alter table public.join_requests
  add constraint join_requests_requested_nome_not_blank
  check (char_length(btrim(requested_nome)) > 0);

alter table public.join_requests
  drop constraint if exists join_requests_requested_cognome_not_blank;

alter table public.join_requests
  add constraint join_requests_requested_cognome_not_blank
  check (char_length(btrim(requested_cognome)) > 0);

create unique index if not exists join_requests_user_pending_unique
  on public.join_requests (requester_user_id)
  where status = 'pending';

create index if not exists join_requests_club_status_idx
  on public.join_requests (club_id, status, created_at);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  club_id bigint not null
    references public.clubs(id) on delete cascade,
  membership_id bigint not null
    references public.memberships(id) on delete cascade,
  requested_by_user_id uuid not null
    references auth.users(id) on delete cascade,
  status text not null default 'pending',
  decided_by_membership_id bigint
    references public.memberships(id) on delete set null,
  decided_at timestamptz,
  cancelled_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint leave_requests_status_check
    check (status in ('pending', 'approved', 'rejected', 'cancelled', 'expired'))
);

create unique index if not exists leave_requests_membership_pending_unique
  on public.leave_requests (membership_id)
  where status = 'pending';

create index if not exists leave_requests_club_status_idx
  on public.leave_requests (club_id, status, created_at);

create or replace function public.touch_clubline_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists clubs_touch_updated_at on public.clubs;

create trigger clubs_touch_updated_at
before update on public.clubs
for each row
execute function public.touch_clubline_updated_at();

drop trigger if exists club_settings_touch_updated_at on public.club_settings;

create trigger club_settings_touch_updated_at
before update on public.club_settings
for each row
execute function public.touch_clubline_updated_at();

drop trigger if exists club_permission_settings_touch_updated_at on public.club_permission_settings;

create trigger club_permission_settings_touch_updated_at
before update on public.club_permission_settings
for each row
execute function public.touch_clubline_updated_at();

drop trigger if exists memberships_touch_updated_at on public.memberships;

create trigger memberships_touch_updated_at
before update on public.memberships
for each row
execute function public.touch_clubline_updated_at();

drop trigger if exists join_requests_touch_updated_at on public.join_requests;

create trigger join_requests_touch_updated_at
before update on public.join_requests
for each row
execute function public.touch_clubline_updated_at();

drop trigger if exists leave_requests_touch_updated_at on public.leave_requests;

create trigger leave_requests_touch_updated_at
before update on public.leave_requests
for each row
execute function public.touch_clubline_updated_at();

insert into storage.buckets (id, name, public)
values ('club-assets', 'club-assets', true)
on conflict (id) do nothing;

alter table if exists public.player_profiles
  add column if not exists club_id bigint references public.clubs(id) on delete cascade;

alter table if exists public.player_profiles
  add column if not exists membership_id bigint references public.memberships(id) on delete set null;

alter table if exists public.player_profiles
  add column if not exists archived_at timestamptz;

alter table if exists public.stream_links
  add column if not exists club_id bigint references public.clubs(id) on delete cascade;

alter table if exists public.lineups
  add column if not exists club_id bigint references public.clubs(id) on delete cascade;

alter table if exists public.attendance_weeks
  add column if not exists club_id bigint references public.clubs(id) on delete cascade;

alter table if exists public.attendance_entries
  add column if not exists club_id bigint references public.clubs(id) on delete cascade;

do $$
declare
  legacy_club_id bigint;
  should_migrate_legacy boolean;
begin
  select
    exists (select 1 from public.player_profiles)
    or exists (select 1 from public.stream_links)
    or exists (select 1 from public.lineups)
    or exists (select 1 from public.attendance_weeks)
    or exists (
      select 1
      from public.team_settings
      where id = 1
        and (
          lower(coalesce(nullif(btrim(team_name), ''), '')) not in ('', 'ultras mentality', 'clubline')
          or crest_url is not null
          or website_url is not null
          or youtube_url is not null
          or discord_url is not null
          or facebook_url is not null
          or instagram_url is not null
          or twitch_url is not null
          or tiktok_url is not null
          or jsonb_array_length(additional_links) > 0
        )
    )
    or exists (
      select 1
      from public.team_permission_settings
      where id = 1
        and (
          vice_manage_players is distinct from true
          or vice_manage_lineups is distinct from true
          or vice_manage_streams is distinct from true
          or vice_manage_attendance is distinct from true
          or vice_manage_team_info is distinct from false
        )
    )
  into should_migrate_legacy;

  if should_migrate_legacy then
    insert into public.clubs (
    name,
    normalized_name,
    slug,
    logo_url,
    primary_color,
    accent_color,
    surface_color
  )
  values (
    coalesce(
      (select nullif(btrim(team_name), '') from public.team_settings where id = 1),
      'Clubline Legacy'
    ),
    lower(
      coalesce(
        (select nullif(btrim(team_name), '') from public.team_settings where id = 1),
        'clubline legacy'
      )
    ),
    'legacy-club',
    (select crest_url from public.team_settings where id = 1),
    '#1F2937',
    '#0F766E',
    '#0F172A'
  )
    on conflict (slug) do update
      set updated_at = timezone('utc', now())
    returning id into legacy_club_id;

    insert into public.club_settings (
    club_id,
    website_url,
    youtube_url,
    discord_url,
    facebook_url,
    instagram_url,
    twitch_url,
    tiktok_url,
    additional_links
  )
  select
    legacy_club_id,
    website_url,
    youtube_url,
    discord_url,
    facebook_url,
    instagram_url,
    twitch_url,
    tiktok_url,
    additional_links
    from public.team_settings
    where id = 1
    on conflict (club_id) do update
      set website_url = excluded.website_url,
          youtube_url = excluded.youtube_url,
          discord_url = excluded.discord_url,
          facebook_url = excluded.facebook_url,
          instagram_url = excluded.instagram_url,
          twitch_url = excluded.twitch_url,
          tiktok_url = excluded.tiktok_url,
          additional_links = excluded.additional_links,
          updated_at = timezone('utc', now());

    insert into public.club_permission_settings (
    club_id,
    vice_manage_players,
    vice_manage_lineups,
    vice_manage_streams,
    vice_manage_attendance,
    vice_manage_team_info
  )
  select
    legacy_club_id,
    vice_manage_players,
    vice_manage_lineups,
    vice_manage_streams,
    vice_manage_attendance,
    vice_manage_team_info
    from public.team_permission_settings
    where id = 1
    on conflict (club_id) do update
      set vice_manage_players = excluded.vice_manage_players,
          vice_manage_lineups = excluded.vice_manage_lineups,
          vice_manage_streams = excluded.vice_manage_streams,
          vice_manage_attendance = excluded.vice_manage_attendance,
          vice_manage_team_info = excluded.vice_manage_team_info,
          updated_at = timezone('utc', now());

    update public.player_profiles
    set club_id = legacy_club_id
    where club_id is null;

    update public.stream_links
    set club_id = legacy_club_id
    where club_id is null;

    update public.lineups
    set club_id = legacy_club_id
    where club_id is null;

    update public.attendance_weeks
    set club_id = legacy_club_id
    where club_id is null;

    update public.attendance_entries
    set club_id = legacy_club_id
    where club_id is null;

    insert into public.memberships (
    club_id,
    auth_user_id,
    role,
    status
  )
  select
    legacy_club_id,
    player.auth_user_id,
    player.team_role,
    'active'
    from public.player_profiles as player
    where player.auth_user_id is not null
      and player.archived_at is null
      and not exists (
        select 1
        from public.memberships as membership
        where membership.auth_user_id = player.auth_user_id
          and membership.status = 'active'
      );

    update public.player_profiles as player
    set membership_id = membership.id
    from public.memberships as membership
    where player.auth_user_id is not null
      and membership.auth_user_id = player.auth_user_id
      and membership.status = 'active'
      and player.membership_id is null;
  end if;
end;
$$;

alter table public.player_profiles
  alter column club_id set not null;

alter table public.stream_links
  alter column club_id set not null;

alter table public.lineups
  alter column club_id set not null;

alter table public.attendance_weeks
  alter column club_id set not null;

alter table public.attendance_entries
  alter column club_id set not null;

alter table public.attendance_weeks
  drop constraint if exists attendance_weeks_week_start_key;

drop index if exists player_profiles_id_console_unique;
create unique index if not exists player_profiles_club_console_unique
  on public.player_profiles (club_id, id_console)
  where id_console is not null
    and btrim(id_console) <> ''
    and archived_at is null;

drop index if exists player_profiles_account_email_unique;
create unique index if not exists player_profiles_active_account_email_unique
  on public.player_profiles (lower(account_email))
  where account_email is not null
    and archived_at is null;

drop index if exists player_profiles_auth_user_id_unique;
create unique index if not exists player_profiles_active_auth_user_id_unique
  on public.player_profiles (auth_user_id)
  where auth_user_id is not null
    and archived_at is null;

create unique index if not exists player_profiles_active_membership_unique
  on public.player_profiles (membership_id)
  where membership_id is not null
    and archived_at is null;

create index if not exists player_profiles_club_active_idx
  on public.player_profiles (club_id, archived_at);

create index if not exists stream_links_club_played_on_idx
  on public.stream_links (club_id, played_on desc);

create index if not exists lineups_club_match_datetime_idx
  on public.lineups (club_id, match_datetime);

create index if not exists attendance_weeks_club_week_start_idx
  on public.attendance_weeks (club_id, week_start desc);

create unique index if not exists attendance_weeks_club_week_start_unique
  on public.attendance_weeks (club_id, week_start);

create unique index if not exists attendance_weeks_club_active_unique
  on public.attendance_weeks (club_id)
  where archived_at is null;

create index if not exists attendance_entries_club_date_idx
  on public.attendance_entries (club_id, attendance_date);

commit;
