create table if not exists public.player_profiles (
  id bigint generated by default as identity primary key,
  nome text not null,
  cognome text not null,
  auth_user_id uuid references auth.users(id) on delete set null,
  account_email text,
  shirt_number integer,
  primary_role text,
  secondary_role text,
  secondary_roles text[] not null default '{}'::text[],
  id_console text,
  team_role text not null default 'player',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint player_profiles_nome_not_blank
    check (char_length(btrim(nome)) > 0),
  constraint player_profiles_cognome_not_blank
    check (char_length(btrim(cognome)) > 0),
  constraint player_profiles_team_role_check
    check (team_role in ('player', 'vice_captain', 'captain')),
  constraint player_profiles_account_email_check
    check (
      account_email is null
      or (
        trim(account_email) <> ''
        and position('@' in account_email) > 1
      )
    ),
  constraint player_profiles_secondary_roles_check
    check (
      secondary_roles is not null
      and array_position(secondary_roles, null::text) is null
    )
);

create unique index if not exists player_profiles_auth_user_id_unique
  on public.player_profiles(auth_user_id)
  where auth_user_id is not null;

create unique index if not exists player_profiles_account_email_unique
  on public.player_profiles(lower(account_email))
  where account_email is not null;

create unique index if not exists player_profiles_id_console_unique
  on public.player_profiles(id_console)
  where id_console is not null and btrim(id_console) <> '';

create index if not exists player_profiles_team_role_idx
  on public.player_profiles(team_role);

create or replace function public.touch_player_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists player_profiles_touch_updated_at on public.player_profiles;

create trigger player_profiles_touch_updated_at
before update on public.player_profiles
for each row
execute function public.touch_player_profiles_updated_at();

alter table public.player_profiles enable row level security;

create table if not exists public.team_settings (
  id integer primary key default 1,
  team_name text not null default 'Clubline',
  crest_url text,
  website_url text,
  youtube_url text,
  discord_url text,
  facebook_url text,
  instagram_url text,
  twitch_url text,
  tiktok_url text,
  additional_links jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint team_settings_singleton_check check (id = 1),
  constraint team_settings_additional_links_is_array_check
    check (jsonb_typeof(additional_links) = 'array')
);

insert into public.team_settings (
  id,
  team_name
)
values (1, 'Clubline')
on conflict (id) do nothing;

create or replace function public.touch_team_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists team_settings_touch_updated_at on public.team_settings;

create trigger team_settings_touch_updated_at
before update on public.team_settings
for each row
execute function public.touch_team_settings_updated_at();

alter table public.team_settings enable row level security;

create table if not exists public.team_permission_settings (
  id integer primary key default 1,
  vice_manage_players boolean not null default true,
  vice_manage_lineups boolean not null default true,
  vice_manage_streams boolean not null default true,
  vice_manage_attendance boolean not null default true,
  vice_manage_team_info boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint team_permission_settings_singleton_check check (id = 1)
);

insert into public.team_permission_settings (
  id,
  vice_manage_players,
  vice_manage_lineups,
  vice_manage_streams,
  vice_manage_attendance,
  vice_manage_team_info
)
values (1, true, true, true, true, false)
on conflict (id) do nothing;

create or replace function public.touch_team_permission_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists team_permission_settings_touch_updated_at on public.team_permission_settings;

create trigger team_permission_settings_touch_updated_at
before update on public.team_permission_settings
for each row
execute function public.touch_team_permission_settings_updated_at();

alter table public.team_permission_settings enable row level security;

create table if not exists public.stream_links (
  id bigint generated by default as identity primary key,
  stream_title text not null,
  competition_name text,
  played_on date not null,
  stream_url text not null,
  stream_status text not null default 'ended',
  stream_ended_at timestamptz,
  provider text,
  result text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint stream_links_stream_title_not_blank
    check (char_length(btrim(stream_title)) > 0),
  constraint stream_links_stream_url_not_blank
    check (char_length(btrim(stream_url)) > 0),
  constraint stream_links_status_check
    check (stream_status in ('live', 'ended'))
);

create index if not exists stream_links_played_on_idx
  on public.stream_links (played_on desc);

create index if not exists stream_links_created_at_idx
  on public.stream_links (created_at desc);

create index if not exists stream_links_status_idx
  on public.stream_links (stream_status);

alter table public.stream_links enable row level security;

create table if not exists public.lineups (
  id bigint generated by default as identity primary key,
  competition_name text not null,
  match_datetime timestamptz not null,
  opponent_name text,
  formation_module text not null,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.lineups
  drop constraint if exists lineups_formation_module_check;

alter table public.lineups
  add constraint lineups_formation_module_check
  check (
    formation_module in (
      '3-4-3 IN LINEA',
      '3-4-1-2',
      '3-4-2-1',
      '3-1-4-2',
      '3-5-2',
      '4-3-3 OFFENSIVO',
      '4-3-3 IN LINEA',
      '4-3-1-2',
      '4-3-2-1',
      '4-5-1',
      '4-3-3 CONTENIMENTO',
      '4-5-1 IN LINEA',
      '4-4-2 IN LINEA',
      '4-4-1-1 AVANZATO',
      '4-1-2-1-2 LARGO',
      '4-1-2-1-2 STRETTO',
      '4-2-2-2',
      '4-3-3 DIFENSIVO',
      '4-4-2 CONTENIMENTO',
      '4-2-4',
      '4-1-3-2',
      '4-1-4-1',
      '4-2-1-3',
      '4-2-3-1 STRETTO',
      '4-2-3-1 LARGO',
      '5-2-3',
      '5-2-1-2',
      '5-4-1 IN LINEA',
      '5-3-2'
    )
  );

create table if not exists public.lineup_players (
  id bigint generated by default as identity primary key,
  lineup_id bigint not null
    references public.lineups(id) on delete cascade,
  player_id bigint not null
    references public.player_profiles(id) on delete cascade,
  position_code text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint lineup_players_unique_player_per_lineup
    unique (lineup_id, player_id),
  constraint lineup_players_unique_position_per_lineup
    unique (lineup_id, position_code)
);

create index if not exists lineups_match_datetime_idx
  on public.lineups (match_datetime);

create index if not exists lineup_players_lineup_id_idx
  on public.lineup_players (lineup_id);

create index if not exists lineup_players_player_id_idx
  on public.lineup_players (player_id);

alter table public.lineups enable row level security;
alter table public.lineup_players enable row level security;

create table if not exists public.attendance_weeks (
  id bigint generated by default as identity primary key,
  week_start date not null unique,
  week_end date not null,
  selected_dates date[] not null,
  archived_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  constraint attendance_weeks_week_bounds_check
    check (week_end = week_start + 6),
  constraint attendance_weeks_selected_dates_check
    check (cardinality(selected_dates) > 0)
);

create table if not exists public.attendance_entries (
  id bigint generated by default as identity primary key,
  week_id bigint not null
    references public.attendance_weeks(id) on delete cascade,
  player_id bigint not null
    references public.player_profiles(id) on delete cascade,
  attendance_date date not null,
  availability text not null default 'pending',
  updated_by_player_id bigint
    references public.player_profiles(id) on delete set null,
  updated_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  constraint attendance_entries_unique_player_per_day
    unique (week_id, player_id, attendance_date),
  constraint attendance_entries_availability_check
    check (availability in ('pending', 'yes', 'no'))
);

create index if not exists attendance_weeks_week_start_idx
  on public.attendance_weeks (week_start desc);

create index if not exists attendance_weeks_archived_at_idx
  on public.attendance_weeks (archived_at);

create index if not exists attendance_entries_week_id_idx
  on public.attendance_entries (week_id);

create index if not exists attendance_entries_player_id_idx
  on public.attendance_entries (player_id);

create index if not exists attendance_entries_attendance_date_idx
  on public.attendance_entries (attendance_date);

create or replace function public.attendance_calendar_week_start(
  reference_date date
)
returns date
language sql
immutable
as $$
  select reference_date - (extract(isodow from reference_date)::int - 1);
$$;

create or replace function public.sync_attendance_entries_for_week(
  target_week_id bigint
)
returns void
language sql
as $$
  insert into public.attendance_entries (
    week_id,
    player_id,
    attendance_date,
    availability
  )
  select
    target_week_id,
    player.id,
    selected_day.attendance_date,
    'pending'
  from public.player_profiles as player
  join public.attendance_weeks as week
    on week.id = target_week_id
  cross join unnest(week.selected_dates) as selected_day(attendance_date)
  left join public.attendance_entries as entry
    on entry.week_id = target_week_id
   and entry.player_id = player.id
   and entry.attendance_date = selected_day.attendance_date
  where entry.id is null;
$$;

create or replace function public.create_attendance_week(
  reference_date date,
  selected_dates date[]
)
returns bigint
language plpgsql
as $$
declare
  target_week_start date;
  target_week_end date;
  normalized_dates date[];
  target_week_id bigint;
begin
  if reference_date is null then
    raise exception 'Specifica una data valida per la settimana presenze';
  end if;

  target_week_start := public.attendance_calendar_week_start(reference_date);
  target_week_end := target_week_start + 6;

  select array_agg(distinct selected_date order by selected_date)
    into normalized_dates
  from unnest(selected_dates) as selected_date
  where selected_date between target_week_start and target_week_end;

  if normalized_dates is null or cardinality(normalized_dates) = 0 then
    raise exception 'Seleziona almeno un giorno valido per la settimana scelta';
  end if;

  if exists (
    select 1
    from unnest(selected_dates) as selected_date
    where selected_date < target_week_start
       or selected_date > target_week_end
  ) then
    raise exception 'Tutti i giorni selezionati devono appartenere alla stessa settimana';
  end if;

  if exists (
    select 1
    from public.attendance_weeks
    where archived_at is null
  ) then
    raise exception 'Archivia prima la settimana presenze attiva';
  end if;

  insert into public.attendance_weeks (
    week_start,
    week_end,
    selected_dates
  )
  values (
    target_week_start,
    target_week_end,
    normalized_dates
  )
  returning id into target_week_id;

  perform public.sync_attendance_entries_for_week(target_week_id);

  return target_week_id;
end;
$$;

create or replace function public.archive_attendance_week(
  target_week_id bigint
)
returns bigint
language plpgsql
as $$
declare
  archived_week_id bigint;
begin
  update public.attendance_weeks
  set archived_at = timezone('utc', now())
  where id = target_week_id
    and archived_at is null
  returning id into archived_week_id;

  return archived_week_id;
end;
$$;

create or replace function public.restore_attendance_week(
  target_week_id bigint
)
returns bigint
language plpgsql
as $$
declare
  restored_week_id bigint;
begin
  if exists (
    select 1
    from public.attendance_weeks
    where archived_at is null
      and id <> target_week_id
  ) then
    raise exception 'Esiste gia una settimana presenze attiva';
  end if;

  update public.attendance_weeks
  set archived_at = null
  where id = target_week_id
    and archived_at is not null
  returning id into restored_week_id;

  if restored_week_id is null then
    raise exception 'La settimana selezionata non puo essere ripristinata';
  end if;

  perform public.sync_attendance_entries_for_week(restored_week_id);

  return restored_week_id;
end;
$$;

grant execute on function public.sync_attendance_entries_for_week(bigint)
  to service_role;

grant execute on function public.create_attendance_week(date, date[])
  to service_role;

grant execute on function public.archive_attendance_week(bigint)
  to service_role;

grant execute on function public.restore_attendance_week(bigint)
  to service_role;

revoke all on function public.sync_attendance_entries_for_week(bigint)
  from public, anon, authenticated;

revoke all on function public.create_attendance_week(date, date[])
  from public, anon, authenticated;

revoke all on function public.archive_attendance_week(bigint)
  from public, anon, authenticated;

revoke all on function public.restore_attendance_week(bigint)
  from public, anon, authenticated;

grant usage on schema public to service_role;

grant select, insert, update, delete
  on table public.player_profiles,
           public.team_settings,
           public.team_permission_settings,
           public.stream_links,
           public.lineups,
           public.lineup_players,
           public.attendance_weeks,
           public.attendance_entries
  to service_role;

grant usage, select on all sequences in schema public
  to service_role;

revoke all
  on table public.player_profiles,
           public.team_settings,
           public.team_permission_settings,
           public.stream_links,
           public.lineups,
           public.lineup_players,
           public.attendance_weeks,
           public.attendance_entries
  from anon, authenticated;

alter table public.attendance_weeks enable row level security;
alter table public.attendance_entries enable row level security;
