create table if not exists public.stream_links (
  id bigint generated by default as identity primary key,
  stream_title text not null,
  competition_name text,
  played_on date not null,
  stream_url text not null,
  stream_status text not null default 'ended',
  stream_ended_at timestamptz,
  provider text,
  result text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint stream_links_stream_title_not_blank
    check (char_length(btrim(stream_title)) > 0),
  constraint stream_links_stream_url_not_blank
    check (char_length(btrim(stream_url)) > 0),
  constraint stream_links_status_check
    check (stream_status in ('live', 'ended'))
);

create index if not exists stream_links_played_on_idx
  on public.stream_links (played_on desc);

create index if not exists stream_links_created_at_idx
  on public.stream_links (created_at desc);

create index if not exists stream_links_status_idx
  on public.stream_links (stream_status);

alter table public.stream_links enable row level security;

drop policy if exists stream_links_select_dev on public.stream_links;
drop policy if exists stream_links_insert_dev on public.stream_links;
drop policy if exists stream_links_update_dev on public.stream_links;
drop policy if exists stream_links_delete_dev on public.stream_links;

create policy stream_links_select_dev
  on public.stream_links
  for select
  using (true);

create policy stream_links_insert_dev
  on public.stream_links
  for insert
  with check (true);

create policy stream_links_update_dev
  on public.stream_links
  for update
  using (true)
  with check (true);

create policy stream_links_delete_dev
  on public.stream_links
  for delete
  using (true);
